--Min/Max Value
MIN_ID		=1000		--4 digit, by DataManager::GetDesc()
MAX_ID		=268435455	--9 digit, by DataManager::GetDesc()
MAX_COUNTER	=65535		--max number for adding/removing counters, by card::add_counter(), field::remove_counter()
MAX_NUMBER	=999999999	--Max number allowed in YGOPro
--Card ID
CARD_DBSCG_LIFE							=10000999	--Cards under this card are in the Life Area (Unofficial card)
CARD_BROLYS_RING						=10001092	--Supported by "BT1-077 Paragus, Controller of Monsters"
CARD_GOLDEN_FRIEZA_RESURRECTED_TERROR	=10001100	--Supported by "P-018 Occupation of Evil Frieza"
CARD_MIRACULOUS_COMEBACK_ULTIMATE_GOHAN	=10002008	--Supported by "BT2-021 Sensing Old Kai"
CARD_AWAKENING_EVIL_MAJIN_BUU			=10002030	--Supported by "BT2-027 Awakening Evil Majin Buu"
CARD_MAJIN_BUU_REVIVED					=10002031	--Supported by "BT2-031 Majin Buu's Sealed Ball"
CARD_MAJIN_BUUS_SEALED_BALL				=10002034	--Supported by "BT2-003 Babidi"
CARD_RESTLESS_SPIRIT_SSB_VEGETA			=10002046	--Supported by "P-064 Trunks, Hope at Hand"
CARD_BIG_GETE_STAR						=10002137	--Supported by "BT2-100 Meta-Cooler"
CARD_PLANET_M2							=10003031	--Supported by "BT3-018 Meta-Rilldo, Form Perfected"
CARD_OUT_OF_CONTROL_EVIL_MAJIN_BUU		=10003052	--Supported by "BT3-046 Magician's Father, Bibidi"
CARD_GOING_ALL_IN_SSB_VEGITO			=10003060	--Supported by "P-065 Vegito, Super Warrior Reborn"
CARD_MAIDEN_SQUADRON_LEADER_RIBRIANNE	=10003215	--Supported by "P-052 Ribrianne, Transformation Complete"
CARD_CITY_PATROL_GREAT_SAIYAMAN			=10004031	--Supported by "BT4-035 City Patrol Great Saiyaman 2"
CARD_CITY_PATROL_GREAT_SAIYAMAN_2		=10004039	--Supported by "BT4-027 City Patrol Great Saiyaman"
CARD_IMPENETRABLE_DEFENSE_HIRUDEGARN	=10004041	--Supported by "BT4-038 Hirudegarn, the Wanderer"
CARD_HIRUDEGARN_THE_WANDERER			=10004042	--Supported by "BT4-041 Hidden Darkness Minotia"
CARD_SUPREME_SHOWDOWN_SON_GOKU			=10004195	--Supported by "TB2-005 Supreme Showdown Vegeta"
CARD_HEROIC_DUO_SON_GOHAN				=10004197	--Supported by "TB2-011 Heroic Duo Videl"
CARD_TINY_RIVALS_SON_GOTEN				=10004198	--Supported by "TB2-007 Tiny Rivals Trunks"
CARD_SUPREME_SHOWDOWN_VEGETA			=10004199	--Supported by "TB2-002 Supreme Showdown Son Goku"
CARD_TINY_RIVALS_TRUNKS					=10004202	--Supported by "TB2-004 Tiny Rivals Son Goten"
CARD_SECRET_TREATY_HERCULE				=10004205	--Supported by "TB2-009 Secret Treaty Android 18"
CARD_DARK_DUO_BABIDI					=10004208	--Supported by "TB2-014 Dark Duo Dabura"
CARD_TEST_OF_STRENGTH_SON_GOKU			=10004216	--Supported by "TB2-030 Test of Strength Uub"
CARD_SCUFFLE_TIME_SON_GOTEN				=10004218	--Supported by "TB2-028 Scuffle Time Mr. Buu"
CARD_PAN_PROUDEST_DAUGHTER				=10004219	--Supported by "TB2-029 Hercule, Proudest Grandpa"
CARD_BEGRUDGING_RESPECT_VEGETA			=10004222	--Supported by "TB2-027 Begrudging Respect Piccolo"
CARD_AWKWARD_SITUATION_TRUNKS			=10004223	--Supported by "TB2-032 Awkward Situation Otokosuki"
CARD_BEGRUDGING_RESPECT_PICCOLO			=10004224	--Supported by "TB2-025 Begrudging Respect Vegeta"
CARD_SCUFFLE_TIME_MR_BUU				=10004225	--Supported by "TB2-022 Scuffle Time Son Goten"
CARD_HERCULE_PROUDEST_GRANDPA			=10004226	--Supported by "TB2-023 Pan, Proudest Daughter"
CARD_TEST_OF_STRENGTH_UUB				=10004228	--Supported by "TB2-020 Test of Strength Son Goku"
CARD_AWKWARD_SITUATION_OTOKOSUKI		=10004230	--Supported by "TB2-026 Awkward Situation Trunks"
CARD_FATEFUL_REUNION_SON_GOKU			=10004234	--Supported by "TB2-037 Fateful Reunion Chi-Chi"
CARD_FATEFUL_REUNION_CHI_CHI			=10004236	--Supported by "TB2-035 Fateful Reunion Son Goku"
CARD_DESTINED_CONCLUSION_PICCOLO_JR		=10004238	--Supported by "TB2-045 Destined Conclusion Hero"
CARD_TIEN_SHINHAN_TRADING_MOVES			=10004243	--Supported by "TB2-048 Mercenary Tao, Trading Moves"
CARD_DESTINED_CONCLUSION_HERO			=10004245	--Supported by "TB2-039 Destined Conclusion Piccolo Jr."
CARD_TRUSTING_RELATIONSHIP_KAMI			=10004247	--Supported by "TB2-047 Trusting Relationship Popo"
CARD_TRUSTING_RELATIONSHIP_POPO			=10004248	--Supported by "TB2-046 Trusting Relationship Kami"
CARD_MERCENARY_TAO_TRADING_MOVES		=10004249	--Supported by "TB2-043 Tien Shinhan, Trading Moves"
CARD_UNYIELDING_VICTORY_SON_GOKU		=10004253	--Supported by "TB2-058 Unyielding Victory Jackie Chun"
CARD_TOUGHENED_UP_KRILLIN				=10004256	--Supported by "TB2-056 Toughened Up Chiaotzu"
CARD_UNENDING_MOVES_YAMCHA				=10004257	--Supported by "TB2-055 Unending Moves Tien Shinhan"
CARD_UNENDING_MOVES_TIEN_SHINHAN		=10004258	--Supported by "TB2-054 Unending Moves Yamcha"
CARD_TOUGHENED_UP_CHIAOTZU				=10004259	--Supported by "TB2-053 Toughened Up Krillin"
CARD_MASTER_ROSHI_MARTIAL_MEISTER		=10004260	--Supported by "TB2-063 Master Shen, Martial Meister"
CARD_UNYIELDING_VICTORY_JACKIE_CHUN		=10004261	--Supported by "TB2-051 Unyielding Victory Son Goku"
CARD_MASTER_SHEN_MARTIAL_MEISTER		=10004267	--Supported by "TB2-057 Master Roshi, Martial Meister"
CARD_GRANDPA_GOHAN						=10005007	--Supported by "BT5-007 Grandpa Gohan, to the Rescue" (Note: Common name, might add to card_code later)
CARD_COMBINER_MECHA_PILAF_MACHINE		=10005017	--Supported by "BT5-016 Pilaf, Leader of the Crew"
CARD_PILAF_LEADER_OF_THE_CREW			=10005018	--Supported by "BT5-015 Combiner Mecha Pilaf Machine"
CARD_SHU_TRUSTED_LACKEY					=10005019	--Supported by "BT5-015 Combiner Mecha Pilaf Machine"
CARD_MAI_TRUSTED_LACKEY					=10005020	--Supported by "BT5-015 Combiner Mecha Pilaf Machine"
CARD_KING_PICCOLO_TERROR_UNLEASHED		=10005024	--Supported by "BT5-025 A King's Return to Youth"
CARD_OOLONGS_WISH						=10005027	--Supported by "BT5-014 Scheming Oolong"
CARD_A_KINGS_RETURN_TO_YOUTH			=10005028	--Supported by "BT5-022 King Piccolo, Terror Unleashed"
CARD_DEADLY_DEFENDER_VEGETA				=10005039	--Supported by "BT5-030 Resolute Strength Son Goku"
CARD_INFERNAL_CHAIN_JANEMBA				=10005054	--Supported by "BT5-047 Infernal Chain Janemba"
CARD_SPIRITED_SEARCH_SS_TRUNKS			=10005073	--Supported by "BT5-057 Spirited Search Pan"
--Cards that have the same name (for Auxiliary.card_code)
CARD_SON_GOKU				=1	--Supported by "BT5-003 Oblivious Rampage Son Goku"
CARD_YAMCHA					=2	--Supported by "BT5-013 Puar, Best Pal"
CARD_SUPER_SAIYAN_SON_GOKU	=3	--Supported by "BT5-030 Resolute Strength Son Goku"
CARD_SUPER_SAIYAN_VEGETA	=4	--Supported by "BT5-037 Vexing Outcome Veku"
CARD_GENERAL_RILLDO			=5	--Supported by "BT5-069 Dr. Myuu, Evil Genius"
CARD_GINYU					=6	--Supported by "BT5-096 Bitter Past Ginyu"
--Token
CARD_BT2014_GHOST_TOKEN			=10002139	--Played by "BT2-014 Ghost Attack Super Saiyan 3 Gotenks"
CARD_BT2033_GHOST_TOKEN			=10002142	--Played by "BT2-033 Super Ghost Kamikaze Attack"
CARD_EX0302_GHOST_TOKEN			=10004186	--Played by "EX03-02 Ghost Combo Gotenks"
CARD_BT2087_CELL_JR_TOKEN		=10002144	--Played by "BT2-087 Uncountable Many Cell Jr."
CARD_EX0315_CELL_JR_TOKEN		=10004189	--Played by "EX03-15 Vile Replication Cell"
CARD_BT2102_CHILLEDS_ARMY_TOKEN	=10002146	--Played by "BT2-102 Chilled"
CARD_EX0321_CHILLEDS_ARMY_TOKEN	=10004191	--Played by "EX03-21 Space Pirate Chilled"
CARD_BT2014_SHADOW_TOKEN		=10003137	--Played by "BT2-014 Ghost Attack Super Saiyan 3 Gotenks"
CARD_EX0310_SHADOW_TOKEN		=10004187	--Played by "EX03-10 Nightmare Scythe Goku Black"
CARD_BT4063_MEDA_TOKEN			=10004138	--Played by "BT4-063 Head Honcho Medamatcha"
--EVENT_CUSTOM
CARD_BT1005_CHAMPA		=10001007	--EVENT_CUSTOM+EVENT_COMBO
CARD_BT1008_VADOS		=10001010	--EVENT_CUSTOM+EVENT_ATTACK_END
CARD_BT1087_FRIEZA		=10001102	--EVENT_CUSTOM+EVENT_BLOCK
CARD_BT2003_BABIDI		=10002004	--EVENT_CUSTOM+EVENT_MOVE_LEADER
CARD_BT2010_SS2_VEGETA	=10002012	--EVENT_CUSTOM+EVENT_COMBO_END
CARD_SENSING_OLD_KAI	=10002024	--EVENT_CUSTOM+EVENT_MAIN_PHASE_START
CARD_P028_FRIEZA		=1000039	--EVENT_CUSTOM+EVENT_ACTIVATE_EXTRA_CARD
CARD_BT5002_PILAF		=10005002	--EVENT_CUSTOM+EVENT_TRIGGER_ACTIVATE_MAIN
--Location
LOCATION_ALL			=0xff	--All locations
LOCATION_DECK			=0x01	--Deck
LOCATION_HAND			=0x02	--Hand
LOCATION_COMBO			=0x02	--Combo Area
LOCATION_LEADER			=0x04	--Leader Area
LOCATION_BATTLECARD		=0x04	--Battle Area (Battle Cards)
LOCATION_FIELDCARD		=0x08	--Battle Area ([Field] cards)
LOCATION_ENERGYACTIVE	=0x10	--Energy Area (Active Mode cards)
LOCATION_ENERGYREST		=0x20	--Energy Area (Rest Mode cards)
LOCATION_DROP			=0x20	--Drop Area
LOCATION_LIFE			=0x20	--Life Area
LOCATION_ENERGY			=0x30	--Energy Area
LOCATION_WARP			=0x40	--The Warp
LOCATION_ABSORBED		=0x80	--Cards under other cards
LOCATION_FIELD			=0x100	--Location of [Field] cards
LOCATION_BATTLE			=0x104	--Battle Area
LOCATION_INPLAY			=0x104	--Leader Area + Battle Area
--Location (for redirect)
--If you specify LOCATION_DECK in the redirection effect, the card will return to the top of the deck
LOCATION_DECKBOT	=0x10001	--(unused)
LOCATION_DECKSHF	=0x20001	--(unused)
--Deck Sequence (for Duel.SendtoDeck)
SEQ_DECK_TOP		=0	--Return to the top of the deck
SEQ_DECK_BOTTOM		=1	--Return to the bottom of the deck
SEQ_DECK_SHUFFLE	=2	--Shuffle into the deck
SEQ_DECK_UNEXIST	=-2	--Disappear from the game
--Zone Sequence (for Card.GetSequence, Card.GetPreviousSequence, etc.)
SEQ_MZONE_LEFT		=0	--(reserved) Leftmost Main Monster Zone
SEQ_MZONE_MID_LEFT	=1	--(reserved) Center-left Main Monster Zone
SEQ_MZONE_MID		=2	--(reserved) Center Main Monster Zone
SEQ_MZONE_MID_RIGHT	=3	--(reserved) Center-right Main Monster Zone
SEQ_MZONE_RIGHT		=4	--(reserved) Rightmost Main Monster Zone
SEQ_MZONE_EX_LEFT	=5	--(reserved) Extra Monster Zone
SEQ_SZONE_LEFT		=0	--(reserved) Leftmost Spell & Trap Zone
SEQ_SZONE_MID_LEFT	=1	--(reserved) Center-left Spell & Trap Zone
SEQ_SZONE_MID		=2	--(reserved) Center Spell & Trap Zone
SEQ_SZONE_MID_RIGHT	=3	--(reserved) Center-right Spell & Trap Zone
SEQ_SZONE_RIGHT		=4	--(reserved) Rightmost Spell & Trap Zone
SEQ_FZONE			=5	--Field Zone
--Zone (Location + Sequence, can be used for EFFECT_DISABLE_FIELD)
ZONE_MZONE			=0x7f	--zone=ZONE_MZONE in Duel.SpecialSummon(targets, sumtype, sumplayer, target_player, nocheck, nolimit, pos, zone)
ZONE_MZONE_EX_LEFT	=0x20	--zone=ZONE_MZONE_EX_LEFT in Duel.MoveToField (c, move_player, target_player, dest, pos, enabled, zone)
--Position
POS_FACEUP_ACTIVE	=0x1	--Face-up Active Mode (Untapped)
POS_FACEDOWN_ACTIVE	=0x2	--(unused) Face-down Active Mode (Untapped)
POS_FACEUP_REST		=0x4	--Face-up Rest Mode (Tapped)
POS_FACEDOWN_REST	=0x8	--(unused) Face-down Rest Mode (Tapped)
POS_FACEUP			=0x5	--Face-up
POS_FACEDOWN		=0xa	--Face-down
POS_ACTIVE			=0x3	--(unused) Face-up or face-down Active Mode (Untapped)
POS_REST			=0xc	--(unused) Face-up or face-down Rest Mode (Tapped)
--Card Type
TYPE_MONSTER		=0x1		--(unused)
TYPE_EXTRA			=0x2		--Extra Card
TYPE_TRAP			=0x4		--(unused)
TYPE_NORMAL			=0x10		--(unused)
TYPE_BATTLE			=0x20		--Battle Card
TYPE_FUSION			=0x40		--(unused)
TYPE_RITUAL			=0x80		--(unused)
TYPE_TRAPMONSTER	=0x100		--(unused)
TYPE_SPIRIT			=0x200		--(unused)
TYPE_UNION			=0x400		--(unused)
TYPE_MULTICOLORED	=0x800		--Card that has 2 or more colors
TYPE_NO_SKILL		=0x1000		--Skill-less
TYPE_SYNCHRO		=0x2000		--(unused)
TYPE_TOKEN			=0x4000		--(unused)
TYPE_QUICKPLAY		=0x10000	--(unused)
TYPE_CONTINUOUS		=0x20000	--(unused)
TYPE_EQUIP			=0x40000	--(unused)
TYPE_FIELD			=0x80000	--(unused)
TYPE_COUNTER		=0x100000	--(unused)
TYPE_FLIP			=0x200000	--(unused)
TYPE_TOON			=0x400000	--(unused)
TYPE_LEADER			=0x800000	--Leader Card
TYPE_PENDULUM		=0x1000000	--(unused)
TYPE_SPSUMMON		=0x2000000	--(unused)
TYPE_LINK			=0x4000000	--(unused)
--Color
COLOR_NONE		=0x0	--No color
COLOR_COLORLESS	=0x1f	--Include any color
COLOR_RED		=0x01	--Red
COLOR_BLUE		=0x02	--Blue
COLOR_GREEN		=0x04	--Green
COLOR_YELLOW	=0x08	--Yellow
COLOR_BLACK		=0x10	--Black
--Color combinations
COLORS_RBG		=COLOR_RED+COLOR_BLUE+COLOR_GREEN	--Red, blue and green
--Power
POWER_NONE	=-2	--(reserved) Undefined power
--Combo Power
COMBO_NONE	=-2	--Undefined combo power
--Energy Cost
ENERGY_NONE	=-2	--Undefined energy cost
--<Character>
CHARACTER_CHAMPA					=0x1	--Introduced by "BT1-001 Champa"
CHARACTER_VADOS						=0x4	--Introduced by "BT1-002 Vados"
CHARACTER_HIT						=0x5	--Introduced by "BT1-003 Hit"
CHARACTER_CABBA						=0x7	--Introduced by "BT1-013 Raging Cabba"
CHARACTER_FROST						=0x9	--Introduced by "BT1-015 Terror Assault Frost"
CHARACTER_BOTAMO					=0xb	--Introduced by "BT1-018 Confident Botamo"
CHARACTER_MAGETTA					=0xc	--Introduced by "BT1-020 Iron Wall Magetta"
CHARACTER_UNIVERSE_6_SUPREME_KAI	=0xd	--Introduced by "BT1-022 Universe 6 Supreme Kai"
CHARACTER_SUPREME_KAIS_ATTENDANT	=0xe	--Introduced by "BT1-023 Kai Attendant of Universe 6"
CHARACTER_VEGETA					=0xf	--Introduced by "BT1-028 Vegeta"
CHARACTER_BEERUS					=0x11	--Introduced by "BT1-029 Beerus"
CHARACTER_SON_GOKU					=0x13	--Introduced by "BT1-030 Super Saiyan Blue Son Goku"
CHARACTER_SON_GOHAN_ADOLESCENCE		=0x14	--Introduced by "BT1-034 Mighty Striker Son Gohan"
CHARACTER_SON_GOTEN					=0x16	--Introduced by "BT1-035 Son Goten"
CHARACTER_TRUNKS_YOUTH				=0x17	--Introduced by "BT1-039 Trunks"
CHARACTER_BULMA						=0x18	--Introduced by "BT1-040 Bulma, God Tempter"
CHARACTER_WHIS						=0x19	--Introduced by "BT1-043 Whis, Judge of the Gods"
CHARACTER_PICCOLO					=0x1a	--Introduced by "BT1-045 Boost Attack Piccolo"
CHARACTER_MAJIN_BUU					=0x1c	--Introduced by "BT1-047 Energy Boosted Majin Buu"
CHARACTER_JACO						=0x1e	--Introduced by "BT1-048 Ultimate Judgment Jaco"
CHARACTER_MONAKA					=0x20	--Introduced by "BT1-049 Mysterious Presence Monaka"
CHARACTER_NORTH_KAI					=0x21	--Introduced by "BT1-050 Guardian North Kai"
CHARACTER_BROLY						=0x22	--Introduced by "BT1-057 Broly"
CHARACTER_SON_GOHAN_YOUTH			=0x25	--Introduced by "BT1-061 Friend-Summoning Son Gohan"
CHARACTER_TRUNKS_FUTURE				=0x26	--Introduced by "BT1-067 Implacable Trunks"
CHARACTER_GOTENKS					=0x28	--Introduced by "BT1-070 Super Saiyan Gotenks"
CHARACTER_KRILLIN					=0x29	--Introduced by "BT1-072 Human Shield Krillin"
CHARACTER_PARAGUS					=0x2b	--Introduced by "BT1-077 Paragus, Controller of Monsters"
CHARACTER_BIO_WARRIOR				=0x2c	--Introduced by "BT1-078 Overflowing Bio Warrior Army"
CHARACTER_FRIEZA					=0x2d	--Introduced by "BT1-083 Frieza"
CHARACTER_GINYU						=0x2f	--Introduced by "BT1-085 Ginyu"
CHARACTER_KING_COLD					=0x31	--Introduced by "BT1-091 King Cold, Father of the Emperor"
CHARACTER_SORBET					=0x32	--Introduced by "BT1-092 Sorbet, The Loyal Commander"
CHARACTER_TAGOMA					=0x33	--Introduced by "BT1-093 Tagoma, The Loyal Warrior"
CHARACTER_SHISAMI					=0x34	--Introduced by "BT1-094 Shisami, The Loyal Warrior"
CHARACTER_RECOOME					=0x35	--Introduced by "BT1-096 Ginyu Force Recoome"
CHARACTER_BURTER					=0x36	--Introduced by "BT1-097 Ginyu Force Burter"
CHARACTER_JEICE						=0x37	--Introduced by "BT1-098 Ginyu Force Jeice"
CHARACTER_GULDO						=0x38	--Introduced by "BT1-099 Ginyu Force Guldo"
CHARACTER_DODORIA					=0x39	--Introduced by "BT1-100 Dodoria, The Emperor's Attendant"
CHARACTER_ZARBON					=0x3a	--Introduced by "BT1-101 Zarbon, The Emperor's Attendant"
CHARACTER_APPULE					=0x3b	--Introduced by "BT1-102 Appule"
CHARACTER_SUI						=0x3c	--Introduced by "BT1-103 Sui"
CHARACTER_BANAN						=0x3d	--Introduced by "BT1-104 Banan"
CHARACTER_CUI						=0x3e	--Introduced by "BT1-105 Cui"
CHARACTER_CELL						=0x41	--Introduced by "P-007 Forceful Strike Cell"
CHARACTER_COOLER					=0x43	--Introduced by "P-009 Clan of Terror Cooler"
CHARACTER_BARDOCK					=0x45	--Introduced by "P-010 Intrepid Determination Bardock"
CHARACTER_VEGITO					=0x48	--Introduced by "P-014 Bursting Energy Super Saiyan Vegito"
CHARACTER_GOKU_BLACK				=0x4a	--Introduced by "P-015 Joyful Strike Goku Black Rosé"
CHARACTER_SON_GOHAN_CHILDHOOD		=0x4b	--Introduced by "P-016 Determined Super Saiyan Son Gohan"
CHARACTER_ANDROID_17				=0x4c	--Introduced by "P-017 Chilling Terror Android 17"
CHARACTER_EVIL_WIZARD_BABIDI		=0x4d	--Introduced by "BT2-003 Babidi"
CHARACTER_MIGHTY_MASK				=0x4f	--Introduced by "BT2-016 Mighty Mask, The Mysterious Warrior"
CHARACTER_HERCULE					=0x50	--Introduced by "BT2-017 Hercule, Buu's Assistant"
CHARACTER_VIDEL						=0x51	--Introduced by "BT2-018 Videl, Gohan's Partner"
CHARACTER_EAST_SUPREME_KAI			=0x52	--Introduced by "BT2-019 Foreseeing East Supreme Kai"
CHARACTER_KIBITO					=0x53	--Introduced by "BT2-020 Kibito"
CHARACTER_OLD_KAI					=0x54	--Introduced by "BT2-021 Sensing Old Kai"
CHARACTER_DABURA					=0x55	--Introduced by "BT2-023 Dabura, The Wizard's Right Hand"
CHARACTER_SPOPOVICH					=0x57	--Introduced by "BT2-024 Attendants Spopovich and Yamu"
CHARACTER_YAMU						=0x58	--Introduced by "BT2-024 Attendants Spopovich and Yamu"
CHARACTER_JIREN						=0x59	--Introduced by "BT2-029 Jiren, Fist of Justice"
CHARACTER_ZAMASU					=0x5b	--Introduced by "BT2-034 Fused Zamasu"
CHARACTER_SON_GOHAN_FUTURE			=0x5c	--Introduced by "BT2-039 Raging Spirit Son Gohan"
CHARACTER_BULMA_FUTURE				=0x5d	--Introduced by "BT2-045 Bulma, Supporter of the Future"
CHARACTER_PILAF						=0x5e	--Introduced by "BT2-048 Group Leader Pilaf"
CHARACTER_SHU						=0x5f	--Introduced by "BT2-049 Shu"
CHARACTER_MAI_FUTURE				=0x60	--Introduced by "BT2-050 Mai, Supporter of Hope"
CHARACTER_MAI_YOUTH					=0x61	--Introduced by "BT2-051 Power of Love Mai"
CHARACTER_YAJIROBE_FUTURE			=0x62	--Introduced by "BT2-052 Courageous Heart Yajirobe"
CHARACTER_HARU						=0x63	--Introduced by "BT2-053 Tiny Heroes Haru and Maki"
CHARACTER_MAKI						=0x64	--Introduced by "BT2-053 Tiny Heroes Haru and Maki"
CHARACTER_GREAT_PRIEST				=0x65	--Introduced by "BT2-059 God of the Gods Great Priest"
CHARACTER_ZEN_OH					=0x66	--Introduced by "BT2-060 Zen-Oh, The Plain God"
CHARACTER_GOWASU					=0x67	--Introduced by "BT2-061 Universe 10 Supreme Kai Gowasu"
CHARACTER_ANDROID_18				=0x68	--Introduced by "BT2-070 Diabolical Duo Androids 17 & 18"
CHARACTER_YAMCHA					=0x69	--Introduced by "BT2-082 Yamcha"
CHARACTER_TIEN_SHINHAN				=0x6a	--Introduced by "BT2-083 Martial Expert Tien Shinhan"
CHARACTER_CELL_JR					=0x6b	--Introduced by "BT2-087 Uncountable Many Cell Jr."
CHARACTER_ANDROID_19				=0x6c	--Introduced by "BT2-092 Encroaching Terror Android 19"
CHARACTER_ANDROID_20				=0x6d	--Introduced by "BT2-093 Terrible Creator Android 20"
CHARACTER_ANDROID_16				=0x6e	--Introduced by "BT2-094 Iron Hammer of Justice Android 16"
CHARACTER_KALE						=0x6f	--Introduced by "BT2-095 Hidden Awakening Kale"
CHARACTER_META_COOLER				=0x70	--Introduced by "BT2-100 Meta-Cooler"
CHARACTER_META_COOLER_CORE			=0x72	--Introduced by "BT2-100 Meta-Cooler"
CHARACTER_CHILLED					=0x73	--Introduced by "BT2-102 Chilled"
CHARACTER_CYCLOPIAN_GUARD			=0x74	--Introduced by "BT2-113 Pivotal Defense Cyclopian Guard"
CHARACTER_GUIDE_ROBO				=0x76	--Introduced by "BT2-114 Guide Robo, Usher of Death"
CHARACTER_SALZA						=0x77	--Introduced by "BT2-115 Cooler's Armored Squadron Leader Salza"
CHARACTER_DORE						=0x79	--Introduced by "BT2-116 Cooler's Armored Squadron Dore"
CHARACTER_NEIZ						=0x7a	--Introduced by "BT2-117 Cooler's Armored Squadron Neiz"
CHARACTER_TOBI						=0x7b	--Introduced by "BT2-118 Tobi, The Obedient Soldier"
CHARACTER_CABIRA					=0x7d	--Introduced by "BT2-119 Cabira, The Obedient Soldier"
CHARACTER_GINYU_FORCE				=0x7e	--Introduced by "P-024 Powerful Bond Ginyu Force"
CHARACTER_TRUNKS_XENO				=0x7f	--Introduced by "EX02-01 Time Patrol Trunks"
CHARACTER_MASKED_SAIYAN				=0x81	--Introduced by "EX02-02 Masked Saiyan, the Mysterious Warrior"
CHARACTER_SUPREME_KAI_OF_TIME		=0x82	--Introduced by "EX02-03 Supreme Kai of Time, Continuity Keeper"
CHARACTER_TOWA						=0x83	--Introduced by "EX02-04 Time Ruler Towa"
CHARACTER_MIRA						=0x84	--Introduced by "EX02-05 Mira, From the Darkness"
CHARACTER_SHUN_SHUN					=0x85	--Introduced by "EX02-06 Majin Twin Shun Shun"
CHARACTER_HARU_HARU					=0x86	--Introduced by "EX02-07 Majin Twin Haru Haru"
CHARACTER_PAN						=0x87	--Introduced by "BT3-001 Pan"
CHARACTER_DR_MYUU					=0x89	--Introduced by "BT3-002 Dr. Myuu"
CHARACTER_SON_GOKU_GT				=0x8b	--Introduced by "BT3-003 Victorious Fist Super Saiyan 3 Son Goku"
CHARACTER_TRUNKS_GT					=0x8d	--Introduced by "BT3-010 Reliable Trunks"
CHARACTER_GIRU						=0x8e	--Introduced by "BT3-012 Dependable Robot Giru"
CHARACTER_UUB						=0x8f	--Introduced by "BT3-014 Hidden Power Uub"
CHARACTER_LEDGIC					=0x90	--Introduced by "BT3-015 Bodyguard Ledgic"
CHARACTER_LUUD						=0x92	--Introduced by "BT3-016 Power-absorbing Luud"
CHARACTER_GENERAL_RILLDO			=0x93	--Introduced by "BT3-018 Meta-Rilldo, Form Perfected"
CHARACTER_SUPER_SIGMA				=0x94	--Introduced by "BT3-021 Triple Union Super Sigma"
CHARACTER_NEZI						=0x95	--Introduced by "BT3-022 Commander Nezi"
CHARACTER_NATT						=0x96	--Introduced by "BT3-023 Mega Cannon Sigma, Natt"
CHARACTER_BIZU						=0x97	--Introduced by "BT3-024 Mega Cannon Sigma, Bizu"
CHARACTER_RIBET						=0x98	--Introduced by "BT3-025 Mega Cannon Sigma Ribet"
CHARACTER_TOPPO						=0x99	--Introduced by "BT3-026 Pride and Justice Toppo"
CHARACTER_GRAND_SUPREME_KAI			=0x9a	--Introduced by "BT3-037 Universal Leader, Grand Supreme Kai"
CHARACTER_WEST_SUPREME_KAI			=0x9b	--Introduced by "BT3-039 Majin Defier, West Supreme Kai"
CHARACTER_SOUTH_SUPREME_KAI			=0x9c	--Introduced by "BT3-040 Majin Defier, South Supreme Kai"
CHARACTER_NORTH_SUPREME_KAI			=0x9d	--Introduced by "BT3-041 Majin Defier, North Supreme Kai"
CHARACTER_KIBITO_KAI				=0x9e	--Introduced by "BT3-043 Powers Combined, Kibito Kai"
CHARACTER_EVIL_WIZARD_BIBIDI		=0x9f	--Introduced by "BT3-046 Magician's Father, Bibidi"
CHARACTER_ANDROID_13				=0xa0	--Introduced by "BT3-056 Android 13"
CHARACTER_DR_GERO					=0xa2	--Introduced by "BT3-067 Dr. Gero, Evil's Inventor"
CHARACTER_ANDROID_14				=0xa4	--Introduced by "BT3-071 Unfeeling Destroyer Android 14"
CHARACTER_ANDROID_15				=0xa5	--Introduced by "BT3-073 Unfeeling Destroyer Android 15"
CHARACTER_CAULIFLA					=0xa6	--Introduced by "BT3-078 Unstoppable Ambition Super Saiyan Caulifla"
CHARACTER_SON_GOKU_CHILDHOOD		=0xa8	--Introduced by "BT3-083 Son Goku"
CHARACTER_GINE						=0xab	--Introduced by "BT3-087 Gine, Family of Justice"
CHARACTER_KAKAROT					=0xad	--Introduced by "BT3-091 Kakarot, the Child Who Got Away"
CHARACTER_KING_VEGETA				=0xae	--Introduced by "BT3-092 Absolute Defense Great Ape King Vegeta"
CHARACTER_VEGETA_YOUTH				=0xb0	--Introduced by "BT3-094 Vegeta"
CHARACTER_TORA						=0xb1	--Introduced by "BT3-096 Hidden Power Great Ape Tora"
CHARACTER_FASHA						=0xb2	--Introduced by "BT3-098 Hidden Power Great Ape Fasha"
CHARACTER_SHUGESH					=0xb3	--Introduced by "BT3-100 Unwavering Solidarity Shugesh"
CHARACTER_BORGOS					=0xb4	--Introduced by "BT3-101 Unwavering Solidarity Borgos"
CHARACTER_NAPPA_ADOLESCENCE			=0xb5	--Introduced by "BT3-102 Nappa, Vegeta's Attendant"
CHARACTER_BERGAMO					=0xb6	--Introduced by "BT3-103 Burgeoning Power Bergamo"
CHARACTER_BARDOCK_XENO				=0xb7	--Introduced by "BT3-109 SS3 Bardock, Power Unleashed"
CHARACTER_FU						=0xb8	--Introduced by "BT3-118 Fu, Shrouded in Mystery"
CHARACTER_VEGETA_GT					=0xbb	--Introduced by "P-030 Vegeta, Powerful as Ever"
CHARACTER_BABY						=0xbc	--Introduced by "P-031 Baby, Dawn of Vengeance"
CHARACTER_ROH						=0xc2	--Introduced by "TB1-034 Universe 9 Supreme Kai Roh"
CHARACTER_LAVENDER					=0xc3	--Introduced by "TB1-037 Trio De Dangers Lavender"
CHARACTER_BASIL						=0xc4	--Introduced by "TB1-038 Trio De Dangers Basil"
CHARACTER_CHAPPIL					=0xc5	--Introduced by "TB1-039 Iron Skin Battler Chappil"
CHARACTER_COMFREY					=0xc6	--Introduced by "TB1-040 Universe 9 Striker Comfrey"
CHARACTER_HOP						=0xc7	--Introduced by "TB1-041 Universe 9 Striker Hop"
CHARACTER_OREGANO					=0xc8	--Introduced by "TB1-042 Universe 9 Striker Oregano"
CHARACTER_HYSSOP					=0xc9	--Introduced by "TB1-043 Universe 9 Striker Hyssop"
CHARACTER_SORREL					=0xca	--Introduced by "TB1-044 Sorrel, The Small Warrior"
CHARACTER_ROSELLE					=0xcb	--Introduced by "TB1-045 Universe 9 Striker Roselle"
CHARACTER_OBUNI						=0xcc	--Introduced by "TB1-046 Spectrum Attack Obuni"
CHARACTER_MURICHIM					=0xce	--Introduced by "TB1-047 Murichim"
CHARACTER_BRIANNE_DE_CHATEAU		=0xcf	--Introduced by "TB1-051 Brianne De Chateau"
CHARACTER_RIBRIANNE					=0xd2	--Introduced by "TB1-051 Ribrianne, Maiden of Anger"
CHARACTER_KAKUNSA					=0xd3	--Introduced by "TB1-058 Maiden Squadron Kakunsa"
CHARACTER_ROZIE						=0xd4	--Introduced by "TB1-059 Maiden Squadron Rozie"
CHARACTER_ZARBUTO					=0xd5	--Introduced by "TB1-060 Zarbuto, Maiden Attendant"
CHARACTER_RABANRA					=0xd6	--Introduced by "TB1-061 Rabanra, Maiden Attendant"
CHARACTER_JIMEZE					=0xd7	--Introduced by "TB1-062 Teleporting Jimeze"
CHARACTER_VIKAL						=0xd8	--Introduced by "TB1-063 Vikal, Master of the Sky"
CHARACTER_ZIRLOIN					=0xd9	--Introduced by "TB1-064 Zirloin, Maiden Attendant"
CHARACTER_PRUM						=0xda	--Introduced by "TB1-065 Attack Reflecting Prum"
CHARACTER_HERMILLA					=0xdb	--Introduced by "TB1-066 Hermilla, The Sniper"
CHARACTER_GANOS						=0xdc	--Introduced by "TB1-067 True Form Ganos"
CHARACTER_CAWAY						=0xde	--Introduced by "TB1-069 Caway, Ki Master"
CHARACTER_DERCORI					=0xdf	--Introduced by "TB1-070 Dercori"
CHARACTER_MASTER_ROSHI				=0xe2	--Introduced by "TB1-076 Master Roshi, Forged of Will"
CHARACTER_DYSPO						=0xe3	--Introduced by "TB1-083 Swift Warrior Dyspo"
CHARACTER_VUON						=0xe4	--Introduced by "TB1-084 Hero Combination Vuon"
CHARACTER_KUNSHI					=0xe5	--Introduced by "TB1-085 Hero Combination Kunshi"
CHARACTER_TUPPER					=0xe6	--Introduced by "TB1-086 Hero Combination Tupper"
CHARACTER_ZOIRAY					=0xe7	--Introduced by "TB1-087 Hero Combination Zoiray"
CHARACTER_COCOTTE					=0xe8	--Introduced by "TB1-088 Ki Bomb Support Cocotte"
CHARACTER_KETTOL					=0xe9	--Introduced by "TB1-089 Hero Combination Kettol"
CHARACTER_KAHSERAL					=0xea	--Introduced by "TB1-090 Hand Strike Kahseral"
CHARACTER_MAJIKAYO					=0xeb	--Introduced by "TB1-091 Protean Being Majikayo"
CHARACTER_NARIRAMA					=0xed	--Introduced by "TB1-092 Super Reaction Narirama"
CHARACTER_NIGRISSHI					=0xee	--Introduced by "TB1-093 Cyborg Warrior Nigrisshi"
CHARACTER_KATOPESLA					=0xef	--Introduced by "TB1-094 Katopesla"
CHARACTER_SON_GOHAN_GT				=0xf0	--Introduced by "BT4-006 Blaze of Glory Son Gohan"
CHARACTER_SON_GOTEN_GT				=0xf1	--Introduced by "BT4-007 Extra Strike SS Son Goten"
CHARACTER_BULMA_GT					=0xf2	--Introduced by "BT4-013 Dependable Mom Bulma"
CHARACTER_BULLA						=0xf3	--Introduced by "BT4-014 Saiyan Daughter Bulla"
CHARACTER_MR_BUU					=0xf4	--Introduced by "BT4-015 Mr. Buu"
CHARACTER_KEFLA						=0xf5	--Introduced by "BT4-019 Saiyan Onslaught Kefla"
CHARACTER_HIRUDEGARN				=0xf7	--Introduced by "BT4-024 Hirudegarn"
CHARACTER_TAPION					=0xf9	--Introduced by "BT4-039 Oath's Power, Tapion"
CHARACTER_MINOTIA					=0xfb	--Introduced by "BT4-041 Hidden Darkness Minotia"
CHARACTER_HOI						=0xfc	--Introduced by "BT4-042 Hoi, Emissary of Flame"
CHARACTER_LORD_SLUG					=0xfd	--Introduced by "BT4-047 Lord Slug"
CHARACTER_KING_PICCOLO				=0x100	--Introduced by "BT4-051 Reign of Terror King Piccolo"
CHARACTER_GURU						=0x102	--Introduced by "BT4-052 Gift of Power Guru"
CHARACTER_NAIL						=0x103	--Introduced by "BT4-053 Nail, the Namekian Ace"
CHARACTER_KAMI						=0x104	--Introduced by "BT4-054 Kami, the Watcher"
CHARACTER_DENDE						=0x105	--Introduced by "BT4-055 Kindhearted Namekian Dende"
CHARACTER_POPO						=0x106	--Introduced by "BT4-056 Popo, Guardian's Aide"
CHARACTER_SAONEL					=0x107	--Introduced by "BT4-057 Namekian Duo Saonel"
CHARACTER_PIRINA					=0x108	--Introduced by "BT4-058 Namekian Duo Pirina"
CHARACTER_ANGILA					=0x109	--Introduced by "BT4-062 Adonic Warrior Angila"
CHARACTER_MEDAMATCHA				=0x10a	--Introduced by "BT4-063 Head Honcho Medamatcha"
CHARACTER_TAMBOURINE				=0x10b	--Introduced by "BT4-064 Dark Vassal Tambourine"
CHARACTER_CYMBAL					=0x10d	--Introduced by "BT4-065 Dark Vassal Cymbal"
CHARACTER_DRUM						=0x10e	--Introduced by "BT4-066 Dark Vassal Drum"
CHARACTER_ANILAZA					=0x10f	--Introduced by "BT4-067 Combo Killer Anilaza"
CHARACTER_OX_KING					=0x111	--Introduced by "BT4-088 Ox-King, Dad at Heart"
CHARACTER_CHI_CHI					=0x112	--Introduced by "BT4-089 Dynasty's Solace Chi-Chi"
CHARACTER_SON_GOHAN					=0x113	--Introduced by "BT4-091 Adoptive Father Son Gohan"
CHARACTER_DEMIGRA					=0x117	--Introduced by "BT4-098 Demigra"
CHARACTER_CHRONOA					=0x119	--Introduced by "BT4-104 Time Control Chronoa"
CHARACTER_GRAVY						=0x11a	--Introduced by "BT4-113 Gravy, Lightning's Might"
CHARACTER_PUTINE					=0x11b	--Introduced by "BT4-115 Frigid Blast Putine"
CHARACTER_TOKITOKI					=0x11c	--Introduced by "BT4-119 Tokitoki, Time Creator"
CHARACTER_SON_GOKU_JR				=0x11d	--Introduced by "BT4-123 Distant Descendant, Son Goku Jr."
CHARACTER_PICCOLO_JR				=0x11e	--Introduced by "SD4-01 Piccolo Jr."
CHARACTER_SIDRA						=0x120	--Introduced by "EX03-12 Indiscriminate Obliteration Sidra"
CHARACTER_HELES						=0x121	--Introduced by "EX03-18 Elegant Assistance Heles"
CHARACTER_BELMOD					=0x122	--Introduced by "EX03-24 Clownish Destruction Belmod"
CHARACTER_PUI_PUI					=0x124	--Introduced by "TB2-016 Pui Pui, Magician's Lackey"
CHARACTER_YAKON						=0x125	--Introduced by "TB2-017 Razor's Edge Yakon"
CHARACTER_SON_GOTEN_ADOLESCENCE		=0x126	--Introduced by "TB2-022 Scuffle Time Son Goten"
CHARACTER_TRUNKS_ADOLESCENCE		=0x127	--Introduced by "TB2-026 Awkward Situation Trunks"
CHARACTER_WILD_TIGER				=0x128	--Introduced by "TB2-031 Wild Tiger, the Imposing"
CHARACTER_OTOKOSUKI					=0x129	--Introduced by "TB2-032 Awkward Situation Otokosuki"
CHARACTER_CHIAOTZU					=0x12a	--Introduced by "TB2-044 Best Buddy Chiaotzu"
CHARACTER_HERO						=0x12b	--Introduced by "TB2-045 Destined Conclusion Hero"
CHARACTER_MERCENARY_TAO				=0x12c	--Introduced by "TB2-048 Mercenary Tao, Trading Moves"
CHARACTER_JACKIE_CHUN				=0x12d	--Introduced by "TB2-050 Jackie Chun, the Mysterious Fighter"
CHARACTER_KRILLIN_CHILDHOOD			=0x12e	--Introduced by "TB2-053 Toughened Up Krillin"
CHARACTER_NAM						=0x12f	--Introduced by "TB2-059 Doublechop Nam"
CHARACTER_GIRAN						=0x130	--Introduced by "TB2-060 Ginormous Strength Giran"
CHARACTER_BACTERIAN					=0x131	--Introduced by "TB2-061 Stenchful Bacterian"
CHARACTER_RANFAN					=0x132	--Introduced by "TB2-062 Risque Ranfan"
CHARACTER_MASTER_SHEN				=0x133	--Introduced by "TB2-063 Master Shen, Martial Meister"
CHARACTER_ANNOUNCER					=0x134	--Introduced by "TB2-065 Announcer"
CHARACTER_SON_GOKU_XENO				=0x135	--Introduced by "P-074 Crisis Crusher Son Goku"
CHARACTER_GOGETA					=0x136	--Introduced by "SD6-01 Knockout Strike Gogeta"
CHARACTER_DRAGON_BALL				=0x138	--Introduced by "SD7-01 Dragon Ball"
CHARACTER_SHENRON					=0x13a	--Introduced by "SD7-01 Miraculous Arrival Shenron"
CHARACTER_VEGETA_XENO				=0x13b	--Introduced by "SD7-03 Vegeta, Returned from Darkness"
CHARACTER_OOLONG					=0x13e	--Introduced by "BT5-002 Oolong, Always Wanting More"
CHARACTER_KRILLIN_YOUTH				=0x13f	--Introduced by "BT5-011 Deadly Defender Krillin"
CHARACTER_PUAR						=0x140	--Introduced by "BT5-013 Puar, Best Pal"
CHARACTER_PILAF_MACHINE				=0x141	--Introduced by "BT5-015 Combiner Mecha Pilaf Machine"
CHARACTER_MAI						=0x142	--Introduced by "BT5-018 Mai, Trusted Lackey"
CHARACTER_BANDAGES					=0x143	--Introduced by "BT5-019 Bandages, to the Rescue"
CHARACTER_SPIKE						=0x144	--Introduced by "BT5-020 Spike, to the Rescue"
CHARACTER_FORTUNETELLER_BABA		=0x146	--Introduced by "BT5-021 Baba, Champions' Leader"
CHARACTER_JANEMBA					=0x147	--Introduced by "BT5-027 Janemba"
CHARACTER_VEKU						=0x149	--Introduced by "BT5-037 Vexing Outcome Veku"
CHARACTER_SOUTH_KAI					=0x14a	--Introduced by "BT5-042 South Kai, Keeping Watch"
CHARACTER_WEST_KAI					=0x14b	--Introduced by "BT5-043 West Kai, Keeping Watch"
CHARACTER_EAST_KAI					=0x14c	--Introduced by "BT5-044 East Kai, Keeping Watch"
CHARACTER_KING_YEMMA				=0x14d	--Introduced by "BT5-045 King Yemma, Soul Supervisor"
CHARACTER_SAIKE_DEMON				=0x14e	--Introduced by "BT5-046 Saike Demon, Rockin' Out"
CHARACTER_SUPER_17					=0x150	--Introduced by "BT5-054 Super 17"
CHARACTER_HELL_FIGHTER_17			=0x152	--Introduced by "BT5-066 Hell Fighter 17, Evil Revived"
CHARACTER_NAPPA						=0x153	--Introduced by "BT5-071 Infernal Fighter Nappa"
CHARACTER_BLACK_MASKED_SAIYAN		=0x154	--Introduced by "BT5-105 Black Masked Saiyan"
CHARACTER_GOGETA_BR					=0x155	--Introduced by "P-091 Gogeta"
CHARACTER_BROLY_BR					=0x157	--Introduced by "P-092 Broly"
CHARACTER_KIKONO_BR					=0x158	--Introduced by "TB3-014 Strategic Mind Kikono"
CHARACTER_SON_GOKU_BR				=0x15a	--Introduced by "TB3-021 Son Goku, Striving to be the Best"
CHARACTER_TOOLO						=0x15b	--Introduced by "TB3-030 Toolo, the Seer"
CHARACTER_CHEELAI_BR				=0x15c	--Introduced by "TB3-045 Cheelai, the Beautiful"
CHARACTER_VEGETA_BR					=0x15d	--Introduced by "TB3-051 Vegeta, Striving to be the Best"
CHARACTER_CARGO						=0x15e	--Introduced by "TB3-060 Cargo, Namekian Youth"
CHARACTER_PORUNGA					=0x15f	--Introduced by "TB3-064 Porunga, Saviour of Namekians"
CHARACTER_FRIEZA_BR					=0x160	--Introduced by "TB3-069 Frieza, Army Reborn"
CHARACTER_VEKU_BR					=0x161	--Introduced by "P-095 Veku, Triumphant Might"
CHARACTER_WHIS_BR					=0x162	--Introduced by "P-103 Whis, the Instructor"
CHARACTER_PARAGUS_BR				=0x163	--Introduced by "P-105 Paragus, the Sacrifice"
CHARACTER_SHENRON_BR				=0x164	--Introduced by "P-107 Shenron, Wishing Anew"
CHARACTER_SON_GOTEN_BR				=0x165	--Introduced by "BT6-006 Support Attack Son Goten"
CHARACTER_TRUNKS_YOUTH_BR			=0x166	--Introduced by "BT6-010 Support Attack Trunks"
CHARACTER_BULMA_BR					=0x167	--Introduced by "BT6-011 Bulma, from the Sidelines"
CHARACTER_PICCOLO_BR				=0x168	--Introduced by "BT6-016 Piccolo"
CHARACTER_BERRYBLUE_BR				=0x169	--Introduced by "BT6-019 Berryblue, the Negotiator"
CHARACTER_GOKULE					=0x16a	--Introduced by "BT6-038 Gokule, the Ultimate Option"
CHARACTER_LEMO_BR					=0x16b	--Introduced by "BT6-054 Cheelai and Lemo"
CHARACTER_BEERUS_BR					=0x16c	--Introduced by "BT6-057 Godstrike Beerus"
CHARACTER_WINGS						=0x16d	--Introduced by "BT6-067 Wings, the Morale Booster"
CHARACTER_ZEIUN						=0x16e	--Introduced by "BT6-068 Zeiun, the Loyal"
CHARACTER_BA_BR						=0x16f	--Introduced by "BT6-069 Ties that Bind Ba"
CHARACTER_GOLIAMITE_BR				=0x170	--Introduced by "BT6-070 Goliamite, the New Breed"
CHARACTER_BEETS_BR					=0x171	--Introduced by "BT6-073 Beets"
CHARACTER_BOUJACK					=0x173	--Introduced by "BT6-080 Boujack"
CHARACTER_X_S_CASH					=0x175	--Introduced by "BT6-092 X. S. Cash, the Gazillionaire"
CHARACTER_GOKUA						=0x176	--Introduced by "BT6-095 Quickshift Gokua"
CHARACTER_ZANGYA					=0x177	--Introduced by "BT6-097 Space Pirate Zangya"
CHARACTER_BIDO						=0x178	--Introduced by "BT6-099 Space Pirate Bido"
CHARACTER_BUJIN						=0x179	--Introduced by "BT6-100 Space Pirate Bujin"
CHARACTER_SUPER_DRAGON_BALL			=0x17b	--Introduced by "BT6-106 Super Dragon Balls"
CHARACTER_SUPER_SHENRON				=0x17c	--Introduced by "BT6-106 Super Shenron, the Almighty"
CHARACTER_COMMANDER_RED				=0x17f	--Introduced by "BT6-113 Commander Red, Head of the RR Army"
CHARACTER_ANDROID_8					=0x180	--Introduced by "BT6-114 Bonds of Friendship Android 8"
CHARACTER_VEGETA_JR					=0x182	--Introduced by "P-148 Vegeta Jr., Heroic Successor"
CHARACTER_MUTAITO					=0x183	--Introduced by "P-159 Mutaito, Skill of a Sage"
CHARACTER_RADITZ					=0x184	--Introduced by "BT7-003 Raditz, the Oppressor"
CHARACTER_COCO						=0x185	--Introduced by "BT7-015 Coco, Village Princess"
CHARACTER_COCOS_GRANDPA				=0x186	--Introduced by "BT7-016 Coco's Grandpa, Village Oldster"
CHARACTER_NATADE_VILLAGE_ELDER		=0x187	--Introduced by "BT7-017 Elder, Village Guardian"
CHARACTER_NATADE_VILLAGE_MONSTER	=0x188	--Introduced by "BT7-018 Natade Village Monster"
CHARACTER_NATADE_VILLAGE_SHAMAN		=0x18a	--Introduced by "BT7-019 Shaman, Ritual Master"
CHARACTER_YAJIROBE					=0x18b	--Introduced by "BT7-065 Yajirobe, Lying in Wait"
CHARACTER_SAIBAIMAN					=0x18c	--Introduced by "BT7-068 Saibaimen, Endless Explosions"
CHARACTER_MOGINAN					=0x18d	--Introduced by "DB1-016 Moginan, the Savage Strongman"
CHARACTER_MOGINAN_UNDERLING			=0x18e	--Introduced by "DB1-018 Moginan Underling, Relentless Horde"
CHARACTER_GRAND_KAI					=0x18f	--Introduced by "DB1-033 Grand Kai, the Lazy Instructor"
CHARACTER_BUBBLES					=0x190	--Introduced by "DB1-035 Bubbles"
CHARACTER_DR_BRIEF					=0x191	--Introduced by "DB1-045 Dr. Brief, Father of a Genius"
CHARACTER_BULMAS_MOM				=0x192	--Introduced by "DB1-046 Bulma's Mom, Mother of a Genius"
CHARACTER_TIGHTS					=0x193	--Introduced by "DB1-068 Tights, Sister of a Genius"
CHARACTER_ORACLE_FISH				=0x194	--Introduced by "DB1-070 Oracle Fish"
CHARACTER_ANDROID_21				=0x196	--Introduced by "BT8-024 Android 21"
CHARACTER_DR_UIRO					=0x198	--Introduced by "BT8-039 Dr.Uiro, Destruction Beam"
CHARACTER_DR_KOCHIN					=0x199	--Introduced by "BT8-045 Dr.Uiro & Dr.Kochin"
CHARACTER_KISHIME					=0x19b	--Introduced by "BT8-058 Kishime, Living Weapon"
CHARACTER_EBIFRYA					=0x19c	--Introduced by "BT8-059 Ebifrya, Living Weapon"
CHARACTER_MISOKATSUN				=0x19d	--Introduced by "BT8-060 Misokatsun, Living Weapon"
CHARACTER_BIOMAN					=0x19e	--Introduced by "BT8-061 Bio-Man, Living Weapon"
CHARACTER_DR_LYCHEE					=0x19f	--Introduced by "BT8-089 Dr.Lychee & Hatchhyack"
CHARACTER_HATCHHYACK				=0x1a0	--Introduced by "BT8-089 Dr.Lychee & Hatchhyack"
CHARACTER_TURLES					=0x1a4	--Introduced by "BT8-097 Turles, Ghost Warrior"
CHARACTER_GHOST_WARRIOR				=0x1a5	--Introduced by "BT8-098 Ghost Warriors"
CHARACTER_GODGARDON					=0x1a6	--Introduced by "BT8-099 Defender Godgardon"
CHARACTER_KAWAZU					=0x1a7	--Introduced by "BT8-100 Defender Kawazu"
CHARACTER_MARCARITA					=0x1ab	--Introduced by "BT9-066 Marcarita, Adorable Assailant"
CHARACTER_BLACK_SMOKE_DRAGON		=0x1ac	--Introduced by "BT9-135 Black Smoke Dragon, Eternal Evil"
CHARACTER_CELL_XENO					=0x1ae	--Introduced by "BT9-137 Cell Xeno, Unspeakable Abomination"
CHARACTER_ANATO						=0x1af	--Introduced by "DB2-010 Anato, Gentle Supremacy"
CHARACTER_KURU						=0x1b0	--Introduced by "DB2-013 Kuru, Proud Supremacy"
CHARACTER_SHOSA						=0x1b1	--Introduced by "DB2-016 Feral Strike Shosa"
CHARACTER_MONNA						=0x1b2	--Introduced by "DB2-017 Monna, the Confidence Booster"
CHARACTER_NINK						=0x1b3	--Introduced by "DB2-018 Burly Brawler Nink"
CHARACTER_MAJORA					=0x1b4	--Introduced by "DB2-019 Majora, Unseeing Aid"
CHARACTER_SHANTZA					=0x1b5	--Introduced by "DB2-020 Mirage Maker Shantza"
CHARACTER_GAMISARAS					=0x1b6	--Introduced by "DB2-021 Stealth Silhouette Gamisaras"
CHARACTER_DAMON						=0x1b7	--Introduced by "DB2-022 Damon, Might of Many"
CHARACTER_DR_ROTA					=0x1b8	--Introduced by "DB2-042 Dr. Rota, Unknown Potential"
CHARACTER_FUWA						=0x1ba	--Introduced by "DB2-045 Fuwa, Strategic Supremacy"
CHARACTER_ZIUM						=0x1bb	--Introduced by "DB2-047 Zium, Lucky Air Raid"
CHARACTER_LILIBEU					=0x1bc	--Introduced by "DB2-048 Lilibeu, Wings of Fortune"
CHARACTER_JIRASEN					=0x1bd	--Introduced by "DB2-049 Jirasen, Graceful Wager"
CHARACTER_MURISARM					=0x1be	--Introduced by "DB2-053 Murisarm, Manipulative Blow"
CHARACTER_MECHIORP					=0x1bf	--Introduced by "DB2-054 Mechiorp, Bobbing and Weaving"
CHARACTER_NAPAPA					=0x1c0	--Introduced by "DB2-055 Napapa"
CHARACTER_RUBALT					=0x1c1	--Introduced by "DB2-056 Rubalt"
CHARACTER_JILCOL					=0x1c2	--Introduced by "DB2-057 Jilcol, High Stakes Guardian"
CHARACTER_AGU						=0x1c3	--Introduced by "DB2-060 Agu, Virtuous Supremacy"
CHARACTER_SANKA_KU					=0x1c5	--Introduced by "DB2-074 Sanka Ku, Maiden Dominance"
CHARACTER_SU_ROAS					=0x1c6	--Introduced by "DB2-077 Su Roas, Maiden Augment"
CHARACTER_PELL						=0x1c7	--Introduced by "DB2-088 Pell, Confident Supremacy"
CHARACTER_OGMA						=0x1c8	--Introduced by "DB2-090 Ogma, Compassionate Supremacy"
CHARACTER_ILLE						=0x1ca	--Introduced by "DB2-107 Ille, Dignified Supremacy"
CHARACTER_KHAI						=0x1cc	--Introduced by "DB2-125 Khai, Righteous Supremity"
CHARACTER_SHIN						=0x1cd	--Introduced by "DB2-136 Shin, Noble Supremacy"
CHARACTER_PAPARONI					=0x1ce	--Introduced by "DB2-139 Paparoni, Brilliant Inventor"
CHARACTER_KOICHIARATOR				=0x1cf	--Introduced by "DB2-141 Koichiarator, Menacing Assassin"
CHARACTER_KOITSUKAI					=0x1d0	--Introduced by "DB2-143 Koitsukai, Mechanical Courage"
CHARACTER_PANCHIA					=0x1d1	--Introduced by "DB2-144 Panchia, Robo Warrior"
CHARACTER_BOLLARATOR				=0x1d2	--Introduced by "DB2-145 Bionic Battler Bollarator"
CHARACTER_THE_PREECHO				=0x1d3	--Introduced by "DB2-152 The Preecho"
CHARACTER_VIARA						=0x1d4	--Introduced by "DB2-153 Viara, Everlasting Assault"
CHARACTER_EYRE						=0x1d5	--Introduced by "DB2-155 Eyre, Intellectual Supremacy"
CHARACTER_ARACK						=0x1d6	--Introduced by "DB2-166 Arack & Cucatail, Universe 5 Destroyer & Angel"
CHARACTER_CUCATAIL					=0x1d7	--Introduced by "DB2-166 Arack & Cucatail, Universe 5 Destroyer & Angel"
CHARACTER_LIQUIIR					=0x1d8	--Introduced by "DB2-167 Liquiir & Korun, Universe 8 Destroyer & Angel"
CHARACTER_KORUN						=0x1d9	--Introduced by "DB2-167 Liquiir & Korun, Universe 8 Destroyer & Angel"
CHARACTER_IWNE						=0x1da	--Introduced by "DB2-168 Iwne & Awamo, Universe 1 Destroyer & Angel"
CHARACTER_AWAMO						=0x1db	--Introduced by "DB2-168 Iwne & Awamo, Universe 1 Destroyer & Angel"
CHARACTER_GEENE						=0x1dc	--Introduced by "DB2-169 Geene & Martinne, Universe 12 Destroyer & Angel"
CHARACTER_MARTINNE					=0x1dd	--Introduced by "DB2-169 Geene & Martinne, Universe 12 Destroyer & Angel"
CHARACTER_QUITELA					=0x1de	--Introduced by "DB2-170 Quitela & Conic, Universe 4 Destroyer & Angel"
CHARACTER_CONIC						=0x1df	--Introduced by "DB2-170 Quitela & Conic, Universe 4 Destroyer & Angel"
CHARACTER_MOHITO					=0x1e0	--Introduced by "DB2-171 Sidra & Mohito, Universe 9 Destroyer & Angel"
CHARACTER_MOSCO						=0x1e1	--Introduced by "DB2-172 Mosco & Kampari, Universe 3 Destroyer & Angel"
CHARACTER_KAMPARI					=0x1e2	--Introduced by "DB2-172 Mosco & Kampari, Universe 3 Destroyer & Angel"
CHARACTER_RUMSSHI					=0x1e3	--Introduced by "DB2-173 Rumsshi & Kusu, Universe 10 Destroyer & Angel"
CHARACTER_KUSU						=0x1e4	--Introduced by "DB2-173 Rumsshi & Kusu, Universe 10 Destroyer & Angel"
CHARACTER_SAWAR						=0x1e5	--Introduced by "DB2-176 Heles & Sawar, Universe 2 Destroyer & Angel"
CHARACTER_VEGEKS_XENO				=0x1e6	--Introduced by "SD14-01 Vegeks, the Unsung Fusion Hero"
CHARACTER_FRIEZA_XENO				=0x1e8	--Introduced by "BT10-086 Frieza, Dark Infestation"
CHARACTER_GOTENKS_ADOLESCENCE		=0x1e9	--Introduced by "BT10-092 Gotenks"
CHARACTER_SYN_SHENRON				=0x1ea	--Introduced by "BT10-093 Syn Shenron"
CHARACTER_HAZE_SHENRON				=0x1ec	--Introduced by "BT10-117 Haze Shenron, Venomous Mist"
CHARACTER_MECHIKABURA				=0x1ed	--Introduced by "BT10-141 Mechikabura, the Broken Seal"
CHARACTER_GOGETA_GT					=0x1ee	--Introduced by "BT10-154 SS4 Gogeta, Peerless Fusion"
CHARACTER_GARLIC_JR					=0x1ef	--Introduced by "EX13-26 Garlic Jr., Immortal Agent of Destruction"
--<<Special Trait>>
TRAIT_GOD							=0x2	--Introduced by "BT1-001 Champa"
TRAIT_ALIEN							=0x6	--Introduced by "BT1-003 Hit"
TRAIT_SAIYAN						=0x8	--Introduced by "BT1-013 Raging Cabba"
TRAIT_FRIEZA_CLAN					=0xa	--Introduced by "BT1-015 Terror Assault Frost"
TRAIT_EARTHLING						=0x15	--Introduced by "BT1-034 Mighty Striker Son Gohan"
TRAIT_NAMEKIAN						=0x1b	--Introduced by "BT1-045 Boost Attack Piccolo"
TRAIT_MAJIN							=0x1d	--Introduced by "BT1-047 Energy Boosted Majin Buu"
TRAIT_GALACTIC_PATROL				=0x1f	--Introduced by "BT1-048 Ultimate Judgment Jaco"
TRAIT_BIO_WARRIOR					=0x2a	--Introduced by "BT1-074 Rampaging Lifeform Bio-Broly"
TRAIT_FRIEZAS_ARMY					=0x2e	--Introduced by "BT1-083 Frieza"
TRAIT_GINYU_FORCE					=0x30	--Introduced by "BT1-085 Ginyu"
TRAIT_ANDROID						=0x42	--Introduced by "P-007 Forceful Strike Cell"
TRAIT_EVIL_WIZARD					=0x4e	--Introduced by "BT2-003 Babidi"
TRAIT_DEMON_REALM_RACE				=0x56	--Introduced by "BT2-023 Dabura, The Wizard's Right Hand"
TRAIT_ROBOT							=0x75	--Introduced by "BT2-113 Pivotal Defense Cyclopian Guard"
TRAIT_COOLERS_ARMORED_SQUADRON		=0x78	--Introduced by "BT2-115 Cooler's Armored Squadron Leader Salza"
TRAIT_CHILLEDS_ARMY					=0x7c	--Introduced by "BT2-118 Tobi, The Obedient Soldier"
TRAIT_MACHINE_MUTANT				=0x8a	--Introduced by "BT3-002 Dr. Myuu"
TRAIT_BODYGUARD						=0x91	--Introduced by "BT3-015 Bodyguard Ledgic"
TRAIT_SCIENTIST						=0xa3	--Introduced by "BT3-067 Dr. Gero, Evil's Inventor"
TRAIT_GREAT_APE						=0xaa	--Introduced by "BT3-083 Uncontrollable Great Ape Son Goku"
TRAIT_UNIVERSE_6					=0xbd	--Introduced by "P-043 Caulifla"
TRAIT_DELUSION_WARRIOR				=0xbe	--Introduced by "P-045 Saiyan Delusion Hercule"
TRAIT_UNIVERSE_7					=0xbf	--Introduced by "TB1-001 Vegeta"
TRAIT_TRIO_DE_DANGERS				=0xc0	--Introduced by "TB1-026 Bergamo"
TRAIT_UNIVERSE_9					=0xc1	--Introduced by "TB1-026 Bergamo"
TRAIT_UNIVERSE_10					=0xcd	--Introduced by "TB1-046 Spectrum Attack Obuni"
TRAIT_MAIDEN_SQUADRON				=0xd0	--Introduced by "TB1-051 Brianne De Chateau"
TRAIT_UNIVERSE_2					=0xd1	--Introduced by "TB1-051 Brianne De Chateau"
TRAIT_UNIVERSE_4					=0xdd	--Introduced by "TB1-067 True Form Ganos"
TRAIT_PRIDE_TROOPERS				=0xe0	--Introduced by "TB1-074 Jiren"
TRAIT_UNIVERSE_11					=0xe1	--Introduced by "TB1-074 Jiren"
TRAIT_UNIVERSE_3					=0xec	--Introduced by "TB1-091 Protean Being Majikayo"
TRAIT_PHANTOM_DEMON					=0xf8	--Introduced by "BT4-024 Hirudegarn"
TRAIT_HERO							=0xfa	--Introduced by "BT4-039 Oath's Power, Tapion"
TRAIT_SLUGS_ARMY					=0xfe	--Introduced by "BT4-047 Lord Slug"
TRAIT_DEMON_CLAN					=0x10c	--Introduced by "BT4-064 Dark Vassal Tambourine"
TRAIT_GOKUS_LINEAGE					=0x110	--Introduced by "BT4-071 Bardock"
TRAIT_SPECIAL_MODEL_KIT				=0x115	--Introduced by "BT4-092 Multimech Bulma"
TRAIT_DEMON_GOD						=0x118	--Introduced by "BT4-098 Demigra"
TRAIT_WORLD_TOURNAMENT				=0x123	--Introduced by "TB2-001 Hercule"
TRAIT_SHENRON						=0x139	--Introduced by "SD7-01 Dragon Ball"
TRAIT_DEVIL_CLAN					=0x145	--Introduced by "BT5-020 Spike, to the Rescue"
TRAIT_EVIL_INCARNATE				=0x148	--Introduced by "BT5-027 Supreme Evil Janemba"
TRAIT_DEMON							=0x14f	--Introduced by "BT5-046 Saike Demon, Rockin' Out"
TRAIT_BARDOCKS_CREW					=0x159	--Introduced by "TB3-018 Bardock"
TRAIT_BOUJACK_BRIGADE				=0x174	--Introduced by "BT6-080 Boujack"
TRAIT_AGENT_OF_DESTRUCTION			=0x181	--Introduced by "BT6-120 Vegeta, Agent of Destruction"
TRAIT_MONSTER						=0x189	--Introduced by "BT7-018 Natade Village Monster"
TRAIT_BRAINWASHED					=0x195	--Introduced by "BT8-006 Son Gohan, Brainwashed"
TRAIT_FRENZIED_WARRIOR				=0x19a	--Introduced by "BT8-050 Frenzied Warrior Piccolo"
TRAIT_GHOST_WARRIOR					=0x1a1	--Introduced by "BT8-089 Dr.Lychee & Hatchhyack"
TRAIT_TUFFLE						=0x1a3	--Introduced by "BT8-092 Dr.Lychee, Inception of the Grudge"
TRAIT_HEROIC						=0x1a8	--Introduced by "BT8-125 Vegeta, Prideful Hero"
TRAIT_VILLAINOUS					=0x1a9	--Introduced by "BT8-126 Beerus, Destructive Villain"
TRAIT_DRAGON						=0x1ad	--Introduced by "BT9-135 Black Smoke Dragon, Eternal Evil"
TRAIT_UNIVERSE_1					=0x1b9	--Introduced by "DB2-010 Anato, Gentle Supremacy"
TRAIT_UNIVERSE_12					=0x1c4	--Introduced by "DB2-060 Agu, Virtuous Supremacy"
TRAIT_UNIVERSE_5					=0x1c9	--Introduced by "DB2-090 Ogma, Compassionate Supremacy"
TRAIT_UNIVERSE_8					=0x1cb	--Introduced by "DB2-107 Ille, Dignified Supremacy"
TRAIT_SHADOW_DRAGON					=0x1eb	--Introduced by "BT10-093 Syn Shenron"
--Era
ERA_CHAMPA_SAGA						=0x3	--Introduced by "BT1-001 Champa"
ERA_RESURRECTION_F_SAGA				=0x10	--Introduced by "BT1-028 Super Saiyan Blue Vegeta"
ERA_BATTLE_OF_GODS_SAGA				=0x12	--Introduced by "BT1-029 Beerus, God of Destruction"
ERA_BROLY_SAGA						=0x23	--Introduced by "BT1-057 Broly"
ERA_FRIEZA_SAGA						=0x24	--Introduced by "BT1-059 Awakening Rage Son Goku"
ERA_ANDROID_CELL_SAGA				=0x27	--Introduced by "BT1-067 Implacable Trunks"
ERA_BABIDI_SAGA						=0x3f	--Introduced by "P-003 Super Saiyan 3 Son Goku"
ERA_FUTURE_TRUNKS_SAGA				=0x40	--Introduced by "P-005 Light of Hope Trunks"
ERA_COOLER_SAGA						=0x44	--Introduced by "P-009 Clan of Terror Cooler"
ERA_CHILLED_SAGA					=0x46	--Introduced by "P-010 Intrepid Determination Bardock"
ERA_THE_EVIL_WIZARD_BABIDI_SAGA		=0x47	--Introduced by "P-012 Leap to Victory Dark Prince Vegeta"
ERA_MAJIN_BUU_SAGA					=0x49	--Introduced by "P-014 Bursting Energy Super Saiyan Vegito"
ERA_UNIVERSE_SURVIVAL_SAGA			=0x5a	--Introduced by "BT2-029 Jiren, Fist of Justice"
ERA_META_COOLER_SAGA				=0x71	--Introduced by "BT2-100 Meta-Cooler"
ERA_DARK_DEMON_REALM_SAGA			=0x80	--Introduced by "EX02-01 Time Patrol Trunks"
ERA_BLACK_STAR_DRAGON_BALL_SAGA		=0x88	--Introduced by "BT3-001 Pan"
ERA_BABY_SAGA						=0x8c	--Introduced by "BT3-003 Victorious Fist Super Saiyan 3 Son Goku"
ERA_ANDROID_13_SAGA					=0xa1	--Introduced by "BT3-056 Android 13"
ERA_BARDOCK_SAGA					=0xa7	--Introduced by "BT3-082 Bardock"
ERA_YOUNG_SON_GOKU_SAGA				=0xa9	--Introduced by "BT3-083 Son Goku"
ERA_DRAGON_BALL_MINUS_SAGA			=0xac	--Introduced by "BT3-087 Gine, Family of Justice"
ERA_ORIGINAL						=0xaf	--Introduced by "BT3-092 Absolute Defense Great Ape King Vegeta"
ERA_UNKNOWN							=0xb9	--Introduced by "BT3-118 Fu, Shrouded in Mystery"
ERA_SAIYAN_SAGA						=0xba	--Introduced by "P-042 Great Ape Prince Vegeta"
ERA_HIRUDEGARN_SAGA					=0xf6	--Introduced by "BT4-023 Trunks"
ERA_LORD_SLUG_SAGA					=0xff	--Introduced by "BT4-047 Lord Slug"
ERA_KING_PICCOLO_SAGA				=0x101	--Introduced by "BT4-051 Reign of Terror King Piccolo"
ERA_GALACTIC_PATROLMAN_SAGA			=0x114	--Introduced by "BT4-091 Adoptive Father Son Gohan"
ERA_SPECIAL							=0x116	--Introduced by "BT4-092 Multimech Bulma"
ERA_WORLD_MA_TOURNAMENT_SAGA		=0x11f	--Introduced by "SD4-01 Piccolo Jr."
ERA_JANEMBA_SAGA					=0x137	--Introduced by "SD6-01 Knockout Strike Gogeta"
ERA_FORTUNETELLER_BABA_SAGA			=0x13c	--Introduced by "SD7-05 Mega Focus Son Goku"
ERA_PILAF_SAGA						=0x13d	--Introduced by "BT5-001 Yamcha"
ERA_SUPER_17_SAGA					=0x151	--Introduced by "BT5-054 Super 17"
ERA_DBS_BROLY_SAGA					=0x156	--Introduced by "P-091 Gogeta"
ERA_BOUJACK_SAGA					=0x172	--Introduced by "BT6-079 Son Gohan"
ERA_THE_PATH_TO_POWER_SAGA			=0x17a	--Introduced by "BT6-105 Son Goku"
ERA_CURSE_OF_THE_BLOOD_RUBIES_SAGA	=0x17d	--Introduced by "BT6-107 Son Goku, the Adventure Begins"
ERA_MYSTICAL_ADVENTURE_SAGA			=0x17e	--Introduced by "BT6-108 Quickshift Krillin"
ERA_DR_UIRO_SAGA					=0x197	--Introduced by "BT8-025 Kaio-Ken Son Goku, Strenuous Onslaught"
ERA_HATCHHYACK_SAGA					=0x1a2	--Introduced by "BT8-089 Dr.Lychee & Hatchhyack"
ERA_SHADOW_DRAGON_SAGA				=0x1aa	--Introduced by "BT8-136 SS4 Vegeta, Peak of Primitive Power"
ERA_DARK_EMPIRE_SAGA				=0x1e7	--Introduced by "SD14-01 Vegeks, the Unsung Fusion Hero"
--Name that is part of the character, special trait, or card name of a card
CHAR_CATEGORY_SON_GOHAN				=0xfff	--Supported by "BT2-071 Inherited Will Super Saiyan Son Goku"
NAME_CATEGORY_ANDROID				=0xffe	--Supported by "BT2-093 Terrible Creator Android 20"
NAME_CATEGORY_BABY					=0xffd	--Supported by "BT3-017 Dr. Myuu, Under Baby's Control"
NAME_CATEGORY_SUPREME_KAI			=0xffc	--Supported by "BT3-037 Universal Leader, Grand Supreme Kai"
CHAR_CATEGORY_GT					=0xffb	--Supported by "BT4-009 Power of Friendship Pan"
CHAR_CATEGORY_SON_GOKU				=0xffa	--Supported by "BT4-096 10x Kamehameha"
TRAIT_CATEGORY_UNIVERSE				=0xff9	--Supported by "EX03-25 Zen-Oh"
NAME_CATEGORY_MASKED				=0xff8	--Supported by "EX06-34 Masked Saiyan, Beguiled Warrior"
--<<Special Trait>> exclusive to a skill
TRAIT_DESIRE						=0xff7	--Supported by "BT5-002 Pilaf"
--Reason
--The reason for sending a card to another location
REASON_KO			=0x1		--KO-ed
REASON_RELEASE		=0x2		--(unused)
REASON_TEMPORARY	=0x4		--(unused)
REASON_MATERIAL		=0x8		--(unused)
REASON_SUMMON		=0x10		--(unused)
REASON_BATTLE		=0x20		--Battle destroyed
REASON_EFFECT		=0x40		--Effect
REASON_COST			=0x80		--Cost
REASON_ADJUST		=0x100		--(unused)
REASON_LOST_TARGET	=0x200		--(unused)
REASON_RULE			=0x400		--Rule
REASON_SPSUMMON		=0x800		--(unused)
REASON_DISSUMMON	=0x1000		--(unused)
REASON_AWAKEN		=0x2000		--Moved with [Awaken] (required for "P-017 Chilling Terror Android 17")
REASON_DISCARD		=0x4000		--(unused)
REASON_RDAMAGE		=0x8000		--(unused)
REASON_RRECOVER		=0x10000	--(unused)
REASON_RETURN		=0x20000	--(unused)
REASON_FUSION		=0x40000	--(unused)
REASON_SYNCHRO		=0x80000	--(unused)
REASON_RITUAL		=0x100000	--(unused)
REASON_XYZ			=0x200000	--(unused)
REASON_REPLACE		=0x1000000	--Substituted
REASON_DRAW			=0x2000000	--(unused)
REASON_REDIRECT		=0x4000000	--(unused)
REASON_REVEAL		=0x8000000	--(unused)
REASON_LINK			=0x10000000	--(unused)
REASON_COMBO		=0x20000000	--Comboed
--Location Reason
LOCATION_REASON_TOFIELD	=0x1	--(unused)
LOCATION_REASON_CONTROL	=0x2	--(unused)
LOCATION_REASON_COUNT	=0x4	--(unused, only available in YGOPro Percy)
--Win Reason
WIN_REASON_DECKOUT			=0x2	--Ran out of cards in the deck
WIN_REASON_INVALID			=0x10	--Invalid deck
WIN_REASON_BEERUS			=0x11	--{BT1-029 Beerus, God of Destruction}
WIN_REASON_GOKUGOHAN		=0x12	--{BT2-069 Father-Son Kamehameha Goku&Gohan}
WIN_REASON_VICTORYSTRIKE	=0x13	--[Victory Strike]
--Summon Type
SUMMON_TYPE_NORMAL			=0x10000000	--(unused)
SUMMON_TYPE_ADVANCE			=0x11000000	--(unused)
SUMMON_TYPE_DUAL			=0x12000000	--(unused)
SUMMON_TYPE_FLIP			=0x20000000	--(unused)
SUMMON_TYPE_SPECIAL			=0x40000000	--(unused)
SUMMON_TYPE_SWAP			=0x41000000	--Play with [Swap]
SUMMON_TYPE_UNION			=0x43000000	--Play with [Union]
SUMMON_TYPE_UNION_POTARA	=0x43000100	--Play with [Union-Potara]
SUMMON_TYPE_RITUAL			=0x45000000	--(unused)
SUMMON_TYPE_OVER_REALM		=0x46000000	--Play with [Over Realm]
SUMMON_TYPE_EVOLVE			=0x49000000	--Play with [Evolve]
SUMMON_TYPE_PENDULUM		=0x4a000000	--(unused)
SUMMON_TYPE_LINK			=0x4c000000	--(unused)
--Summon Value
SUMMON_VALUE_SELF					=0x1	--(unused)
SUMMON_VALUE_DARK_FUSION			=0x10	--(unused)
SUMMON_VALUE_BLACK_GARDEN			=0x11	--(unused)
SUMMON_VALUE_SYNCHRO_MATERIAL		=0x12	--(unused)
SUMMON_VALUE_DARK_SANCTUARY			=0x13	--(unused)
SUMMON_VALUE_MILLENNIUM_REVELATION	=0x14	--(unused)
SUMMON_VALUE_LV						=0x1000	--(unused)
SUMMON_VALUE_GLADIATOR				=0x2000	--(unused)
SUMMON_VALUE_EVOLTILE				=0x4000	--(unused)
--Card Status
STATUS_DISABLED				=0x0001		--(unused)
STATUS_TO_ENABLE			=0x0002		--(unused)
STATUS_TO_DISABLE			=0x0004		--(unused)
STATUS_PROC_COMPLETE		=0x0008		--(unused)
STATUS_SET_TURN				=0x0010		--(unused)
STATUS_NO_ENERGY_COST		=0x0020		--No energy cost
STATUS_BATTLE_RESULT		=0x0040		--(unused)
STATUS_SPSUMMON_STEP		=0x0080		--(unused)
STATUS_FORM_CHANGED			=0x0100		--(unused)
STATUS_SUMMONING			=0x0200		--(unused)
STATUS_EFFECT_ENABLED		=0x0400		--(unused)
STATUS_SUMMON_TURN			=0x0800		--(unused)
STATUS_KO_CONFIRMED			=0x1000		--Confirmed to be KO-ed
STATUS_LEAVE_CONFIRMED		=0x2000		--(unused)
STATUS_BATTLE_DESTROYED		=0x4000		--(unused)
STATUS_COPYING_EFFECT		=0x8000		--(unused) Copying another card's effect
STATUS_CHAINING				=0x10000	--(unused)
STATUS_SUMMON_DISABLED		=0x20000	--(unused)
STATUS_ACTIVATE_DISABLED	=0x40000	--(unused)
STATUS_EFFECT_REPLACED		=0x80000	--(unused)
STATUS_EVOLVING				=0x100000	--Evolving
STATUS_ATTACK_CANCELED		=0x200000	--Attacking card's attack is negated
STATUS_INITIALIZING			=0x400000	--(unused)
STATUS_ACTIVATED			=0x800000	--(unused, only available in YGOPro Percy)
STATUS_JUST_POS				=0x1000000	--(unused)
STATUS_CONTINUOUS_POS		=0x2000000	--(unused)
STATUS_FORBIDDEN			=0x4000000	--(unused)
STATUS_ACT_FROM_HAND		=0x8000000	--(unused)
STATUS_OPPO_BATTLE			=0x10000000	--Battled against opponent's card
STATUS_ACTIVE_BE_ATTACKED	=0x20000000	--Can be attacked while in Active Mode
STATUS_SPSUMMON_TURN		=0x40000000	--(unused)
--Assume
ASSUME_CODE			=1	--(unused)
ASSUME_TYPE			=2	--(unused)
ASSUME_LEVEL		=3	--(unused)
ASSUME_RANK			=4	--(unused)
ASSUME_ATTRIBUTE	=5	--(unused)
ASSUME_RACE			=6	--(unused)
ASSUME_ATTACK		=7	--(unused)
ASSUME_DEFENSE		=8	--(unused)
ASSUME_LINK			=9	--(unused, only available in YGOPro Percy)
ASSUME_LINKMARKER	=10	--(unused, only available in YGOPro Percy)
--Link Marker
LINK_MARKER_BOTTOM_LEFT		=0x001	--(unused)
LINK_MARKER_BOTTOM			=0x002	--(unused)
LINK_MARKER_BOTTOM_RIGHT	=0x004	--(unused)
LINK_MARKER_LEFT			=0x008	--(unused)
LINK_MARKER_RIGHT			=0x020	--(unused)
LINK_MARKER_TOP_LEFT		=0x040	--(unused)
LINK_MARKER_TOP				=0x080	--(unused)
LINK_MARKER_TOP_RIGHT		=0x100	--(unused)
--Counter
COUNTER_WITHOUT_PERMIT	=0x1000	--(unused)
COUNTER_NEED_ENABLE		=0x2000	--(unused)
--Phase
PHASE_DRAW			=0x01	--Draw Phase
PHASE_STANDBY		=0x02	--Standby Phase
PHASE_MAIN1			=0x04	--Main Phase 1
PHASE_BATTLE_START	=0x08	--Start Step
PHASE_BATTLE_STEP	=0x10	--Battle Step
PHASE_DAMAGE		=0x20	--Damage Step
PHASE_DAMAGE_CAL	=0x40	--Damage calculation
PHASE_BATTLE		=0x80	--End Step
PHASE_MAIN2			=0x100	--Main Phase 2
PHASE_END			=0x200	--End Phase
--Player
PLAYER_ONE		=0		--Player who goes first
PLAYER_TWO		=1		--Player who goes second
PLAYER_NONE		=2		--No players
PLAYER_ALL		=3		--All players
PLAYER_OWNER	=nil	--player=PLAYER_OWNER in Duel.Sendto..(targets, player, reason)
PLAYER_SELF		=0		--player=PLAYER_SELF in Effect.SetCondition(Auxiliary.Function(player)), etc.
PLAYER_OPPO		=1		--player=PLAYER_OPPO in Effect.SetCondition(Auxiliary.Function(player)), etc.
--Chain Information
CHAININFO_CHAIN_COUNT			=0x01	--(unused)
CHAININFO_TRIGGERING_EFFECT		=0x02	--(unused)
CHAININFO_TRIGGERING_PLAYER		=0x04	--(unused)
CHAININFO_TRIGGERING_CONTROLER	=0x08	--(unused)
CHAININFO_TRIGGERING_LOCATION	=0x10	--(unused)
CHAININFO_TRIGGERING_SEQUENCE	=0x20	--(unused)
CHAININFO_TARGET_CARDS			=0x40	--(unused)
CHAININFO_TARGET_PLAYER			=0x80	--(unused)
CHAININFO_TARGET_PARAM			=0x100	--(unused)
CHAININFO_DISABLE_REASON		=0x200	--(unused)
CHAININFO_DISABLE_PLAYER		=0x400	--(unused)
CHAININFO_CHAIN_ID				=0x800	--(unused)
CHAININFO_TYPE					=0x1000	--(unused)
CHAININFO_EXTTYPE				=0x2000	--(unused)
CHAININFO_TRIGGERING_POSITION	=0x4000	--(unused)
--The following is not available in YGOPro Percy
CHAININFO_TRIGGERING_CODE		=0x8000		--(unused)
CHAININFO_TRIGGERING_CODE2		=0x10000	--(unused)
CHAININFO_TRIGGERING_LEVEL		=0x40000	--(unused)
CHAININFO_TRIGGERING_RANK		=0x80000	--(unused)
CHAININFO_TRIGGERING_ATTRIBUTE	=0x100000	--(unused)
CHAININFO_TRIGGERING_RACE		=0x200000	--(unused)
CHAININFO_TRIGGERING_ATTACK		=0x400000	--(unused)
CHAININFO_TRIGGERING_DEFENSE	=0x800000	--(unused)
--Reset
RESET_SELF_TURN		=0x10000000	--Reset on own turn (combined with RESET_PHASE)
RESET_OPPO_TURN		=0x20000000	--Reset on opponent's turn (combined with RESET_PHASE)
RESET_PHASE			=0x40000000	--Reset in a specific phase (combined with PHASE constant)
RESET_CHAIN			=0x80000000	--Reset when a Chain resolves
RESET_EVENT			=0x1000		--Reset under a specified condition (combined with following events)
RESET_CARD			=0x2000		--(unused)
RESET_CODE			=0x4000		--(unused)
RESET_COPY			=0x8000		--Reset the copied effect
--The following is used in combination with RESET_EVENT in SetReset
RESET_DISABLE		=0x00010000	--Reset when effect is negated (only applicable to owner==effect handler)
RESET_TURN_SET		=0x00020000	--(unused)
RESET_TOGRAVE		=0x00040000	--(unused)
RESET_REMOVE		=0x00080000	--(unused)
RESET_TEMP_REMOVE	=0x00100000	--(unused)
RESET_TOHAND		=0x00200000	--(unused)
RESET_TODECK		=0x00400000	--(unused)
RESET_LEAVE			=0x00800000	--(unused)
RESET_TOFIELD		=0x01000000	--(unused)
RESET_CONTROL		=0x02000000	--(unused)
RESET_OVERLAY		=0x04000000	--(unused)
RESET_MSCHANGE		=0x08000000	--(unused)
--Reset combinations
RESETS_STANDARD		=0x1fe0000	--RESET_TURN_SET+RESET_TOGRAVE+RESET_REMOVE+RESET_TEMP_REMOVE+RESET_TOHAND+RESET_TODECK+RESET_LEAVE+RESET_TOFIELD
RESETS_REDIRECT		=0xc7e0000	--RESETS_STANDARD+RESET_OVERLAY+RESET_MSCHANGE-RESET_LEAVE-RESET_TOFIELD (EFFECT_LEAVE_FIELD_REDIRECT)
--Effect Type
--Classification of effects
EFFECT_TYPE_SINGLE		=0x0001	--Effect applied to only a single card on the field
EFFECT_TYPE_FIELD		=0x0002	--Effect applied to all cards/players in a location
EFFECT_TYPE_EQUIP		=0x0004	--(unused)
EFFECT_TYPE_ACTIONS		=0x0008	--(unused)
EFFECT_TYPE_ACTIVATE	=0x0010	--Card activation
EFFECT_TYPE_FLIP		=0x0020	--(unused)
EFFECT_TYPE_IGNITION	=0x0040	--(unused)
EFFECT_TYPE_TRIGGER_O	=0x0080	--Optional Trigger Effect
EFFECT_TYPE_QUICK_O		=0x0100	--Optional Quick Effect
EFFECT_TYPE_TRIGGER_F	=0x0200	--Mandatory Trigger Effect
EFFECT_TYPE_QUICK_F		=0x0400	--Mandatory Quick Effect
EFFECT_TYPE_CONTINUOUS	=0x0800	--Continuous Effect, non-Chaining effect
EFFECT_TYPE_XMATERIAL	=0x1000	--(unused)
EFFECT_TYPE_GRANT		=0x2000	--Effect granted to another card
EFFECT_TYPE_TARGET		=0x4000	--(unused, not available in YGOPro Percy)
--Flag
--Characteristics of effects
EFFECT_FLAG_INITIAL				=0x0001		--(unused)
EFFECT_FLAG_FUNC_VALUE			=0x0002		--(unused)
EFFECT_FLAG_COUNT_LIMIT			=0x0004		--(unused)
EFFECT_FLAG_FIELD_ONLY			=0x0008		--(unused)
EFFECT_FLAG_CARD_TARGET			=0x0010		--Targets cards
EFFECT_FLAG_IGNORE_RANGE		=0x0020		--Affects cards in all locations
EFFECT_FLAG_ABSOLUTE_TARGET		=0x0040		--(unused)
EFFECT_FLAG_IGNORE_IMMUNE		=0x0080		--Ignores effect immunity
EFFECT_FLAG_SET_AVAILABLE		=0x0100		--Affects face-down cards on the field
EFFECT_FLAG_CANNOT_NEGATE		=0x0200		--(unused)
EFFECT_FLAG_CANNOT_DISABLE		=0x0400		--Cannot be negated
EFFECT_FLAG_PLAYER_TARGET		=0x0800		--Targets players
EFFECT_FLAG_BOTH_SIDE			=0x1000		--(unused)
EFFECT_FLAG_COPY_INHERIT		=0x2000		--(unused)
EFFECT_FLAG_DAMAGE_STEP			=0x4000		--Can be activated during the Damage Step (not required for EFFECT_TYPE_SINGLE)
EFFECT_FLAG_DAMAGE_CAL			=0x8000		--Can be activated during damage calculation (not required for EFFECT_TYPE_SINGLE)
EFFECT_FLAG_DELAY				=0x10000	--Optional Trigger Effect cannot miss timing
EFFECT_FLAG_SINGLE_RANGE		=0x20000	--Sets the range of EFFECT_TYPE_SINGLE effects
EFFECT_FLAG_UNCOPYABLE			=0x40000	--Cannot be copied
EFFECT_FLAG_OATH				=0x80000	--(unused)
EFFECT_FLAG_SPSUM_PARAM			=0x100000	--(unused)
EFFECT_FLAG_REPEAT				=0x200000	--(unused)
EFFECT_FLAG_NO_TURN_RESET		=0x400000	--"Once while face-up on the field"
EFFECT_FLAG_EVENT_PLAYER		=0x800000	--(unused)
EFFECT_FLAG_OWNER_RELATE		=0x1000000	--(unused)
EFFECT_FLAG_AVAILABLE_BD		=0x2000000	--(N/A)
EFFECT_FLAG_CLIENT_HINT			=0x4000000	--Enables a tooltip of the effect (can only be used outside initial_effect)
EFFECT_FLAG_IGNORE_CHAIN_LIMIT	=0x8000000	--Can Chain to EFFECT_FLAG_CHAIN_LIMIT effects
EFFECT_FLAG_CHAIN_LIMIT			=0x10000000	--Cannot be Chained to
EFFECT_FLAG_IGNORE_BARRIER		=0x20000000	--Ignores [Barrier]
EFFECT_FLAG_KEYSKILL			=0x40000000	--[Keyword] skill
EFFECT_FLAG_IMMEDIATELY_APPLY	=0x80000000	--(unused)

EFFECT_FLAG2_NAGA				=0x0001		--(N/A)
EFFECT_FLAG2_COF				=0x0002		--(unused)
EFFECT_FLAG2_MAJESTIC_MUST_COPY	=0x80000000	--(unused, only available in YGOPro Percy)
--Effect Code
EFFECT_IMMUNE_EFFECT				=1		--Unaffected by card effects
EFFECT_DISABLE						=2		--Effects negated (not applied during effect resolution)
EFFECT_CANNOT_DISABLE				=3		--(unused)
EFFECT_SET_CONTROL					=4		--(unused)
EFFECT_CANNOT_CHANGE_CONTROL		=5		--(unused)
EFFECT_CANNOT_ACTIVATE				=6		--Player cannot activate effects
EFFECT_CANNOT_TRIGGER				=7		--Card cannot activate effects
EFFECT_DISABLE_EFFECT				=8		--Effects negated (applied during effect resolution)
EFFECT_DISABLE_CHAIN				=9		--(unused)
EFFECT_DISABLE_TRAPMONSTER			=10		--(unused)
EFFECT_CANNOT_INACTIVATE			=12		--(unused)
EFFECT_CANNOT_DISEFFECT				=13		--Effect cannot be negated
EFFECT_CANNOT_CHANGE_POSITION		=14		--Cannot change position
EFFECT_TRAP_ACT_IN_HAND				=15		--(unused)
EFFECT_TRAP_ACT_IN_SET_TURN			=16		--(unused)
EFFECT_REMAIN_FIELD					=17		--(unused)
EFFECT_MONSTER_SSET					=18		--(unused)
EFFECT_CANNOT_SUMMON				=20		--Cannot Normal Summon monsters
EFFECT_CANNOT_FLIP_SUMMON			=21		--(unused)
EFFECT_CANNOT_PLAY					=22		--Cannot play non-Extra Cards
EFFECT_CANNOT_MSET					=23		--Cannot Set monsters
EFFECT_CANNOT_SSET					=24		--Cannot Set Spells/Traps
EFFECT_CANNOT_DRAW					=25		--Cannot draw cards
EFFECT_CANNOT_DISABLE_SUMMON		=26		--(unused)
EFFECT_CANNOT_DISABLE_SPSUMMON		=27		--(unused)
EFFECT_SET_SUMMON_COUNT_LIMIT		=28		--(unused)
EFFECT_EXTRA_SUMMON_COUNT			=29		--(unused)
EFFECT_PLAY_CONDITION				=30		--Play conditions
EFFECT_REVIVE_LIMIT					=31		--(unused)
EFFECT_SUMMON_PROC					=32		--(unused)
EFFECT_LIMIT_SUMMON_PROC			=33		--(unused)
EFFECT_SPSUMMON_PROC				=34		--(unused)
EFFECT_EXTRA_SET_COUNT				=35		--(unused)
EFFECT_SET_PROC						=36		--(unused)
EFFECT_LIMIT_SET_PROC				=37		--(unused)
EFFECT_DEVINE_LIGHT					=38		--(unused)
EFFECT_CANNOT_DISABLE_FLIP_SUMMON	=39		--(unused)
EFFECT_CANNOT_BE_KOED				=40		--Cannot be KO-ed
EFFECT_CANNOT_BE_KOED_EFFECT		=41		--Cannot be KO-ed by effects
EFFECT_CANNOT_BE_KOED_BATTLE		=42		--Cannot be KO-ed by battle
EFFECT_UNRELEASABLE_SUM				=43		--(unused)
EFFECT_UNRELEASABLE_NONSUM			=44		--(unused)
EFFECT_DESTROY_SUBSTITUTE			=45		--(unused)
EFFECT_CANNOT_RELEASE				=46		--(unused)
EFFECT_CANNOT_BE_KOED_COUNT			=47		--Cannot be KO-ed a number of times
EFFECT_UNRELEASABLE_EFFECT			=48		--(unused)
EFFECT_DESTROY_REPLACE				=50		--Substitute a card being destroyed with another action
EFFECT_RELEASE_REPLACE				=51		--(unused)
EFFECT_SEND_REPLACE					=52		--Put a card into another location instead of X
EFFECT_CANNOT_DISCARD_HAND			=55		--(unused)
EFFECT_CANNOT_DISCARD_DECK			=56		--(unused)
EFFECT_CANNOT_USE_AS_COST			=57		--(unused)
EFFECT_CANNOT_PLACE_COUNTER			=58		--(unused)
EFFECT_CANNOT_TO_GRAVE_AS_COST		=59		--(unused)
EFFECT_LEAVE_FIELD_REDIRECT			=60		--(unused)
EFFECT_TO_HAND_REDIRECT				=61		--(unused)
EFFECT_TO_DECK_REDIRECT				=62		--(unused)
EFFECT_TO_ENERGY_REDIRECT			=63		--Put a card into another location instead of the Energy Area
EFFECT_DROP_REDIRECT				=64		--Put a card into another location instead of the Drop Area
EFFECT_CANNOT_TO_HAND				=65		--Cannot be put into the hand
EFFECT_CANNOT_TO_DECK				=66		--Cannot be put into the deck
EFFECT_CANNOT_DROP					=67		--Cannot be put into the Drop Area
EFFECT_CANNOT_TO_ENERGY				=68		--Cannot be put into the Energy Area
EFFECT_CANNOT_TURN_SET				=69		--(unused)
EFFECT_CANNOT_BE_BATTLE_TARGET		=70		--Cannot be targeted for attacks
EFFECT_CANNOT_BE_EFFECT_TARGET		=71		--Cannot be targeted by effects
EFFECT_IGNORE_BATTLE_TARGET			=72		--(unused)
EFFECT_CANNOT_DIRECT_ATTACK			=73		--Cannot attack directly
EFFECT_DIRECT_ATTACK				=74		--(unused)
EFFECT_DUAL_STATUS					=75		--(unused)
EFFECT_EQUIP_LIMIT					=76		--(unused)
EFFECT_DUAL_SUMMONABLE				=77		--(unused)
EFFECT_REVERSE_DAMAGE				=80		--(unused)
EFFECT_REVERSE_RECOVER				=81		--(unused)
EFFECT_CHANGE_DAMAGE				=82		--Change the value of the damage inflicted to a player
EFFECT_REFLECT_DAMAGE				=83		--(unused)
EFFECT_CANNOT_ATTACK				=85		--Cannot attack
EFFECT_CANNOT_ATTACK_ANNOUNCE		=86		--Cannot declare attack
EFFECT_CANNOT_CHANGE_POS_E			=87		--Cannot change position by effects
EFFECT_ACTIVATE_COST				=90		--Add activation cost
EFFECT_SUMMON_COST					=91		--(unused)
EFFECT_SPSUMMON_COST				=92		--(unused)
EFFECT_FLIPSUMMON_COST				=93		--(unused)
EFFECT_MSET_COST					=94		--(unused)
EFFECT_SSET_COST					=95		--(unused)
EFFECT_ATTACK_COST					=96		--Add attack cost

EFFECT_UPDATE_POWER					=100	--Increase/decrease power
EFFECT_SET_ATTACK					=101	--(unused)
EFFECT_SET_ATTACK_FINAL				=102	--(unused)
EFFECT_SET_BASE_ATTACK				=103	--(unused)
EFFECT_UPDATE_COMBO_POWER			=104	--Increase/decrease combo power
EFFECT_SET_DEFENSE					=105	--(unused)
EFFECT_SET_DEFENSE_FINAL			=106	--(unused)
EFFECT_SET_BASE_DEFENSE				=107	--Set original DEF
EFFECT_REVERSE_UPDATE				=108	--(unused)
EFFECT_SWAP_AD						=109	--(unused)
EFFECT_SWAP_BASE_AD					=110	--(unused)
EFFECT_SWAP_ATTACK_FINAL			=111	--(N/A)
EFFECT_SWAP_DEFENSE_FINAL			=112	--(N/A)
EFFECT_ADD_CODE						=113	--(unused)
EFFECT_CHANGE_CODE					=114	--(unused)
EFFECT_ADD_TYPE						=115	--(unused)
EFFECT_REMOVE_TYPE					=116	--Remove card type
EFFECT_CHANGE_TYPE					=117	--(unused)
EFFECT_ADD_RACE						=120	--(unused)
EFFECT_REMOVE_RACE					=121	--(unused)
EFFECT_CHANGE_RACE					=122	--(unused)
EFFECT_ADD_COLOR					=125	--Add color
EFFECT_REMOVE_ATTRIBUTE				=126	--(unused)
EFFECT_CHANGE_ATTRIBUTE				=127	--(unused)
EFFECT_UPDATE_TOTAL_ENERGY_COST		=130	--Increase/decrease total energy cost
EFFECT_CHANGE_TOTAL_ENERGY_COST		=131	--Set total energy cost
EFFECT_UPDATE_RANK					=132	--(unused)
EFFECT_CHANGE_RANK					=133	--(unused)
EFFECT_UPDATE_LSCALE				=134	--(unused)
EFFECT_CHANGE_LSCALE				=135	--(unused)
EFFECT_UPDATE_RSCALE				=136	--(unused)
EFFECT_CHANGE_RSCALE				=137	--(unused)
EFFECT_SET_POSITION					=140	--(unused)
EFFECT_SELF_DESTROY					=141	--(unused)
EFFECT_SELF_TOGRAVE					=142	--(unused)
EFFECT_DOUBLE_TRIBUTE				=150	--(unused)
EFFECT_DECREASE_TRIBUTE				=151	--(unused)
EFFECT_DECREASE_TRIBUTE_SET			=152	--(unused)
EFFECT_EXTRA_RELEASE				=153	--(unused)
EFFECT_TRIBUTE_LIMIT				=154	--(unused)
EFFECT_EXTRA_RELEASE_SUM			=155	--(unused)
EFFECT_TRIPLE_TRIBUTE				=156	--(N/A)
EFFECT_ADD_EXTRA_TRIBUTE			=157	--(unused, not available in YGOPro Percy)
EFFECT_EXTRA_RELEASE_NONSUM			=158	--(unused, not available in YGOPro Percy)
EFFECT_COMBOING						=160	--Comboing (in the Combo Area)
EFFECT_COUNTER_PERMIT				=0x10000--(unused)
EFFECT_COUNTER_LIMIT				=0x20000--(unused)
EFFECT_RCOUNTER_REPLACE				=0x30000--(unused)
EFFECT_LPCOST_CHANGE				=170	--(unused)
EFFECT_LPCOST_REPLACE				=171	--(unused)
EFFECT_SKIP_DP						=180	--Skip Draw Phase
EFFECT_SKIP_SP						=181	--Skip Standby Phase
EFFECT_SKIP_M1						=182	--(unused) Skip Main Phase 1
EFFECT_SKIP_BP						=183	--(unused) Skip Battle Phase
EFFECT_SKIP_M2						=184	--(unused) Skip Main Phase 2
EFFECT_CANNOT_BP					=185	--(unused) Cannot conduct Battle Phase
EFFECT_CANNOT_M2					=186	--Cannot conduct Main Phase 2
EFFECT_CANNOT_EP					=187	--(unused) Cannot conduct End Phase
EFFECT_SKIP_TURN					=188	--Skip the entire turn
EFFECT_DEFENSE_ATTACK				=190	--(unused)
EFFECT_MUST_ATTACK					=191	--(unused)
EFFECT_FIRST_ATTACK					=192	--(unused)
EFFECT_ATTACK_ALL					=193	--(unused)
EFFECT_EXTRA_ATTACK					=194	--Increase the number of attacks
EFFECT_MUST_BE_ATTACKED				=195	--(unused, only available in YGOPro Percy)
EFFECT_ONLY_BE_ATTACKED				=196	--(unused)
EFFECT_ATTACK_DISABLED				=197	--(unused)
EFFECT_NO_BATTLE_DAMAGE				=200	--(unused)
EFFECT_AVOID_BATTLE_DAMAGE			=201	--Take no battle damage from attacks involving this card
EFFECT_REFLECT_BATTLE_DAMAGE		=202	--(unused)
EFFECT_PIERCE						=203	--(unused)
EFFECT_BATTLE_DESTROY_REDIRECT		=204	--(unused)
EFFECT_BATTLE_DAMAGE_TO_EFFECT		=205	--(unused)
EFFECT_BOTH_BATTLE_DAMAGE			=206	--(unused, not available in YGOPro Percy)
EFFECT_ALSO_BATTLE_DAMAGE			=207	--(unused, not available in YGOPro Percy)
EFFECT_CHANGE_BATTLE_DAMAGE			=208	--(unused, not available in YGOPro Percy)
EFFECT_TOSS_COIN_REPLACE			=220	--(unused)
EFFECT_TOSS_DICE_REPLACE			=221	--(unused)
EFFECT_FUSION_MATERIAL				=230	--(unused)
EFFECT_CHAIN_MATERIAL				=231	--(unused)
EFFECT_SYNCHRO_MATERIAL				=232	--(unused)
EFFECT_XYZ_MATERIAL					=233	--(unused)
EFFECT_FUSION_SUBSTITUTE			=234	--(unused)
EFFECT_CANNOT_BE_FUSION_MATERIAL	=235	--(unused)
EFFECT_CANNOT_BE_SYNCHRO_MATERIAL	=236	--(unused)
EFFECT_SYNCHRO_MATERIAL_CUSTOM		=237	--(unused)
EFFECT_CANNOT_BE_XYZ_MATERIAL		=238	--(unused)
EFFECT_CANNOT_BE_LINK_MATERIAL		=239	--(unused)
EFFECT_SYNCHRO_LEVEL				=240	--(unused)
EFFECT_RITUAL_LEVEL					=241	--(unused)
EFFECT_XYZ_LEVEL					=242	--(unused)
EFFECT_EXTRA_RITUAL_MATERIAL		=243	--(unused)
EFFECT_NONTUNER						=244	--(unused)
EFFECT_OVERLAY_REMOVE_REPLACE		=245	--(unused)
EFFECT_SCRAP_CHIMERA				=246	--(unused)
EFFECT_TUNE_MAGICIAN_X				=247	--(unused)
EFFECT_TUNE_MAGICIAN_F				=248	--(unused, not available in YGOPro Percy)
EFFECT_PRE_MONSTER					=250	--(unused)
EFFECT_MATERIAL_CHECK				=251	--Check the card that was Evolved ("P-052 Ribrianne, Transformation Complete")
EFFECT_DISABLE_FIELD				=260	--(unused)
EFFECT_USE_EXTRA_MZONE				=261	--(unused)
EFFECT_USE_EXTRA_SZONE				=262	--(unused)
EFFECT_MAX_MZONE					=263	--(unused)
EFFECT_MAX_SZONE					=264	--(unused)
EFFECT_FORCE_MZONE					=265	--(unused, only available in YGOPro Percy)
EFFECT_BECOME_LINKED_ZONE			=266	--(unused, only available in YGOPro Percy)
EFFECT_HAND_LIMIT					=270	--Change the hand size limit
EFFECT_DRAW_COUNT					=271	--(unused)
EFFECT_SPIRIT_DONOT_RETURN			=280	--(unused)
EFFECT_SPIRIT_MAYNOT_RETURN			=281	--(unused)
EFFECT_CHANGE_ENVIRONMENT			=290	--(unused)
EFFECT_NECRO_VALLEY					=291	--(unused)
EFFECT_FORBIDDEN					=292	--(unused)
EFFECT_NECRO_VALLEY_IM				=293	--(unused)
EFFECT_REVERSE_DECK					=294	--(unused)
EFFECT_REMOVE_BRAINWASHING			=295	--(unused)
EFFECT_BP_TWICE						=296	--(unused)
EFFECT_UNIQUE_CHECK					=297	--(unused)
EFFECT_MATCH_KILL					=300	--(unused)
EFFECT_SYNCHRO_CHECK				=310	--(unused)
EFFECT_QP_ACT_IN_NTPHAND			=311	--(unused)
EFFECT_MUST_BE_MATERIAL				=312	--(unused, only available in YGOPro Percy)
EFFECT_TO_GRAVE_REDIRECT_CB			=313	--(unused)
EFFECT_CHANGE_LEVEL_FINAL			=314	--(unused, only available in YGOPro Percy)
EFFECT_CHANGE_RANK_FINAL			=315	--(unused, only available in YGOPro Percy)
EFFECT_MUST_BE_FMATERIAL			=316	--(unused, only available in YGOPro Percy)
EFFECT_MUST_BE_XMATERIAL			=317	--(unused, only available in YGOPro Percy)
EFFECT_MUST_BE_LMATERIAL			=318	--(unused, only available in YGOPro Percy)
EFFECT_SPSUMMON_PROC_G				=320	--(unused)
EFFECT_SPSUMMON_COUNT_LIMIT			=330	--(unused)
EFFECT_LEFT_SPSUMMON_COUNT			=331	--(unused)
EFFECT_CANNOT_SELECT_BATTLE_TARGET	=332	--Cannot target cards for attacks
EFFECT_CANNOT_SELECT_EFFECT_TARGET	=333	--(unused)
EFFECT_ADD_SETCODE					=334	--Add setname
EFFECT_ADD_CHARACTER				=334	--Add <character name> (refer to CharacterList)
EFFECT_ADD_SPECIAL_TRAIT			=334	--Add <<special trait>> (refer to SpecialTraitList)
EFFECT_NO_EFFECT_DAMAGE				=335	--(unused)
EFFECT_UNSUMMONABLE_CARD			=336	--(unused, only available in YGOPro Percy)
EFFECT_DISABLE_CHAIN_FIELD			=337	--(N/A)
EFFECT_DISCARD_COST_CHANGE			=338	--(unused)
EFFECT_HAND_SYNCHRO					=339	--(unused)
EFFECT_ADD_FUSION_CODE				=340	--(unused)
EFFECT_ADD_FUSION_SETCODE			=341	--(unused)
EFFECT_RISE_TO_FULL_HEIGHT			=342	--(unused, only available in YGOPro Percy)
EFFECT_ONLY_ATTACK_MONSTER			=343	--(unused)
EFFECT_MUST_ATTACK_MONSTER			=344	--(unused)
EFFECT_PATRICIAN_OF_DARKNESS		=345	--(unused)
EFFECT_EXTRA_ATTACK_MONSTER			=346	--(unused)
EFFECT_UNION_STATUS					=347	--(unused)
EFFECT_OLDUNION_STATUS				=348	--(unused)
EFFECT_ADD_FUSION_ATTRIBUTE			=349	--(unused, reserved)
EFFECT_REMOVE_FUSION_ATTRIBUTE		=350	--(unused, reserved)
EFFECT_CHANGE_FUSION_ATTRIBUTE		=351	--(unused)
EFFECT_EXTRA_FUSION_MATERIAL		=352	--(unused)
EFFECT_TUNER_MATERIAL_LIMIT			=353	--(unused)
EFFECT_ADD_LINK_CODE				=354	--(unused)
EFFECT_ADD_LINK_SETCODE				=355	--(unused, reserved)
EFFECT_ADD_LINK_ATTRIBUTE			=356	--(unused, not available in YGOPro Percy)
EFFECT_ADD_LINK_RACE				=357	--(unused, not available in YGOPro Percy)
EFFECT_EXTRA_MATERIAL				=358	--(unused, only available in YGOPro Percy)
EFFECT_QP_ACT_IN_SET_TURN			=359	--(unused, not available in YGOPro Percy)
EFFECT_EXTRA_PENDULUM_SUMMON		=360	--(unused, not available in YGOPro Percy)
EFFECT_MATERIAL_LIMIT				=361	--(unused, not available in YGOPro Percy)
EFFECT_SET_BATTLE_ATTACK			=362	--(unused, not available in YGOPro Percy)
EFFECT_SET_BATTLE_DEFENSE			=363	--(unused, not available in YGOPro Percy)
--The following is only available in YGOPro Percy
EFFECT_CANNOT_LOSE_DECK				=400	--Cannot lose when decking out
EFFECT_CANNOT_LOSE_LIFE				=401	--Cannot lose when running out of life
EFFECT_CANNOT_LOSE_EFFECT			=402	--(unused)
EFFECT_BP_FIRST_TURN				=403	--(unused)
EFFECT_UNSTOPPABLE_ATTACK			=404	--(unused)
EFFECT_ALLOW_NEGATIVE				=405	--(unused)
EFFECT_SELF_ATTACK					=406	--(unused)
EFFECT_BECOME_QUICK					=407	--(unused)
EFFECT_LEVEL_RANK					=408	--(unused)
EFFECT_RANK_LEVEL					=409	--(unused)
EFFECT_LEVEL_RANK_S					=410	--(unused)
EFFECT_RANK_LEVEL_S					=411	--(unused)
EFFECT_UPDATE_LINK					=420	--(unused)
EFFECT_CHANGE_LINK					=421	--(unused)
EFFECT_CHANGE_LINK_FINAL			=422	--(unused)
EFFECT_ADD_LINKMARKER				=423	--(unused)
EFFECT_REMOVE_LINKMARKER			=424	--(unused)
EFFECT_CHANGE_LINKMARKER			=425	--(unused)
--The following is only available in YGOPro DS
EFFECT_LIFE_CARD					=500	--Card in the Life Area
EFFECT_CHARGE_TURN					=501	--Check if a player has placed a card in their Energy Area during their Charge Phase
EFFECT_REST_MODE					=502	--Workaround to switch an Extra Card to Rest Mode ("BT2-122 Big Gete Star")
EFFECT_DAMAGE_TURN					=503	--Check if a card has dealt damage during the damage step this turn
EFFECT_AWAKEN						=600	--[Awaken] ("BT1-001 God of Destruction Champa")
EFFECT_DOUBLE_STRIKE				=601	--[Double Strike] ("BT1-001 God of Destruction Champa")
EFFECT_ATTACK_ACTIVE_MODE			=602	--Attack Battle Cards in Active Mode ("BT1-002 Vados")
EFFECT_EVOLVE						=603	--[Evolve] ("BT1-004 Destructive Terror Champa")
EFFECT_TRIPLE_STRIKE				=604	--[Triple Strike] ("BT1-004 Destructive Terror Champa")
EFFECT_DUAL_ATTACK					=605	--[Dual Attack] ("BT1-008 Bewitching God Vados")
EFFECT_BLOCKER						=606	--[Blocker] ("BT1-019 Botamo of Universe 6")
EFFECT_CRITICAL						=607	--[Critical] ("BT1-028 Vegeta")
EFFECT_QUADRUPLE_STRIKE				=608	--[Quadruple Strike] ("BT1-043 Whis, Judge of the Gods")
EFFECT_CANNOT_NEGATE_ATTACK			=609	--Cannot negate attack ("BT1-043 Whis, Judge of the Gods")
EFFECT_IGNORE_AWAKEN_CONDITION		=610	--Activate [Awaken] even if player has 5 or more life ("BT1-051 Result of Training")
EFFECT_REVENGE						=611	--[Revenge] ("BT1-066 Tenacious Vegeta")
EFFECT_FIELD						=612	--[Field] ("BT1-081 Broly's Ring")
EFFECT_UNION_POTARA					=613	--[Union-Potara] ("BT2-012 Repeated Force Vegito")
EFFECT_UNION_FUSION					=614	--[Union-Fusion] ("BT2-015 Prodigy Fusion Super Saiyan Gotenks")
EFFECT_PLAY_WITHOUT_PAYING			=615	--Play a Battle Card without paying its energy cost ("BT2-018 Videl, Gohan's Partner")
EFFECT_UNION_ABSORB					=616	--[Union-Absorb] ("BT2-027 Awakening Evil Majin Buu")
EFFECT_NEGATE_ACTIVATE_EFFECT		=617	--Negate [Activate] effect ("BT2-040 Restless Spirit SSB Vegeta")
EFFECT_INDESTRUCTIBLE				=618	--[Indestructible] ("BT2-056 Zamasu, The Alert God")
EFFECT_UNLIMITED_COPIES				=619	--Include as many copies in your deck as you like ("BT2-107 Infinite Multiplication Meta-Cooler")
EFFECT_COMBO_REST_MODE				=620	--Combo in Rest Mode ("BT2-112 Chilled, Army General")
EFFECT_GAIN_COMBO_COST				=621	--Gain 0 combo cost ("BT2-112 Chilled, Army General")
EFFECT_ULTIMATE						=622	--[Ultimate] ("BT2-123 Ultimate Force SSB Vegito")
EFFECT_TRIPLE_ATTACK				=623	--[Triple Attack] ("BT2-123 Ultimate Force SSB Vegito")
EFFECT_OVER_REALM					=624	--[Over Realm] ("EX02-01 Time Patrol Trunks")
EFFECT_EX_EVOLVE					=625	--[EX-Evolve] ("BT3-003 Victorious Fist Super Saiyan 3 Son Goku")
EFFECT_BARRIER						=626	--[Barrier] ("BT3-008 Fearless Pan")
EFFECT_SUPER_COMBO					=627	--[Super Combo] ("BT3-013 Handy Giru")
EFFECT_LIMIT_ENERGY					=628	--Restrict the amount of energy a player can place ("BT3-032 Son Goku")
EFFECT_CANNOT_COMBO					=629	--Player cannot combo ("BT3-033 Ultra Instinct -Sign- Son Goku")
EFFECT_BATTLE_AREA_USE_AS_COST		=630	--Can be used to pay energy costs while in the Battle Area ("BT3-039 Majin Defier, West Supreme Kai")
EFFECT_LEAVE_REPLACE				=631	--Prevent a card from leaving the Battle Area ("BT3-051 God Absorber Majin Buu")
EFFECT_CHANGE_AWAKEN_LIFE			=632	--Change a player's life condition for [Awaken] ("BT3-056 Android 13")
EFFECT_UPDATE_COMBO_COST			=633	--Increase/decrease combo cost ("BT3-092 Absolute Defense Great Ape King Vegeta")
EFFECT_XENO_EVOLVE					=634	--[Xeno-Evolve] ("BT3-109 SS3 Bardock, Power Unleashed")
EFFECT_CANNOT_LOSE					=635	--Player cannot lose the game ("P-032 Kaio-Ken Son Goku")
EFFECT_CANNOT_WIN					=636	--Player cannot win the game ("P-032 Kaio-Ken Son Goku")
EFFECT_UPDATE_GREEN_SKILL_COST		=637	--Increase/decrease green specified skill cost ("P-033 Endless Evolution Broly")
EFFECT_UPDATE_RED_SKILL_COST		=638	--(reserved) Increase/decrease red specified skill cost
EFFECT_UPDATE_BLUE_SKILL_COST		=639	--(reserved) Increase/decrease blue specified skill cost
EFFECT_UPDATE_YELLOW_SKILL_COST		=640	--(reserved) Increase/decrease yellow specified skill cost
EFFECT_UPDATE_COLORLESS_SKILL_COST	=641	--Increase/decrease (unspecified) skill cost ("P-064 Trunks, Hope at Hand")
EFFECT_UPDATE_GREEN_PLAY_COST		=642	--Increase/decrease green specified energy cost ("P-033 Endless Evolution Broly")
EFFECT_UPDATE_RED_PLAY_COST			=643	--(reserved) Increase/decrease red specified energy cost
EFFECT_UPDATE_BLUE_PLAY_COST		=644	--(reserved) Increase/decrease blue specified energy cost
EFFECT_UPDATE_YELLOW_PLAY_COST		=645	--(reserved) Increase/decrease yellow specified energy cost
EFFECT_WARRIOR_OF_UNIVERSE_7		=646	--[Warrior of Universe 7] ("TB1-001 Vegeta")
EFFECT_NO_SPECIFIED_COST			=647	--No specified cost ("TB1-001 Vegeta")
EFFECT_CANNOT_DECK_NONUNIVERSE_7	=648	--Player cannot include non-<<Universe 7>> cards in their deck ("TB1-050 Son Goku")
EFFECT_VICTORY_STRIKE				=649	--[Victory Strike] ("TB1-097 Son Goku, The Awakened Power")
EFFECT_DEFLECT						=650	--[Deflect] ("BT4-004 Untapped Power SS3 Son Goku")
EFFECT_BOND							=651	--[Bond] ("BT4-046 Piccolo, Kami's Successor")
EFFECT_ACTIVATE_WITHOUT_PAYING		=652	--Activate an Extra Card's skill without paying its energy cost ("BT4-070 Sacrifice")
EFFECT_SWAP							=653	--[Swap] ("BT4-076 Abrupt Breakthrough Son Goku")
EFFECT_WORMHOLE						=654	--[Wormhole] ("BT4-098 Ghastly Malice Demigra")
EFFECT_DARK_OVER_REALM				=655	--[Dark Over Realm] ("BT4-106 Dark Control Demon God Demigra")
EFFECT_CANNOT_DECK_NONUNIVERSE		=656	--Player cannot include non-<<Universe>> cards in their deck ("EX03-25 Zen-Oh")
EFFECT_OVER_REALM_TURN				=657	--Check if a card was played with [Over Realm] this turn ("P-060 Desperate Onslaught Bardock")
EFFECT_CANNOT_DECK_NONTOURNAMENT	=658	--Player cannot include non-<<World Tournament>> cards in their deck ("TB2-065 Announcer")
EFFECT_CANNOT_DECK_COST_6_MORE		=659	--Player cannot include cards with energy costs of 6 or more in their deck ("P-069 Son Goku & Vegeta")
EFFECT_BURST						=660	--[Burst] ("BT5-001 Yamcha")
EFFECT_SPARKING						=661	--[Sparking] ("BT5-001 Yamcha, the Hungry Wolf")
EFFECT_DRAGON_BALL					=662	--[Dragon Ball] ("BT5-002 Pilaf")
EFFECT_WISH							=663	--[Wish] ("BT5-002 Pilaf")
EFFECT_CANNOT_DECK_COST_5_MORE		=664	--Player cannot include cards with energy costs of 5 or more in their deck ("P-086 Janemba")
--Event Code
--Events that can be used as a trigger for Trigger Effects
EVENT_STARTUP				=1000	--(unused)
EVENT_FLIP					=1001	--(unused)
EVENT_FREE_CHAIN			=1002	--Open window to activate Ignition and Trigger Effects
EVENT_DESTROY				=1010	--(unused)
EVENT_DROP					=1011	--When a card is placed in the Drop Area
EVENT_TO_ENERGY_REST		=1011	--When a card is placed in the Energy Area in Rest Mode
EVENT_TO_HAND				=1012	--(unused)
EVENT_TO_DECK				=1013	--(unused)
EVENT_WARP					=1013	--When a card is sent to the Warp
EVENT_TO_ENERGY				=1014	--When a card is placed in the Energy Area in Active Mode
EVENT_LEAVE_FIELD			=1015	--When a card is removed from the Battle Area
EVENT_CHANGE_POS			=1016	--When a card position is changed
EVENT_RELEASE				=1017	--(unused)
EVENT_DISCARD				=1018	--(unused)
EVENT_LEAVE_FIELD_P			=1019	--(unused)
EVENT_CHAIN_SOLVING			=1020	--(unused)
EVENT_CHAIN_ACTIVATING		=1021	--(unused)
EVENT_CHAIN_SOLVED			=1022	--(unused)
EVENT_CHAIN_ACTIVATED		=1023	--(N/A)
EVENT_CHAIN_NEGATED			=1024	--(unused)
EVENT_CHAIN_DISABLED		=1025	--(unused)
EVENT_CHAIN_END				=1026	--(unused)
EVENT_CHAINING				=1027	--When a card/effect is activating in response to another card/effect
EVENT_BECOME_TARGET			=1028	--(unused)
EVENT_KOED					=1029	--When a card is KO-ed
EVENT_MOVE					=1030	--(unused, not available in YGOPro Percy)
EVENT_ADJUST				=1040	--After adjusting the adjust_all() card
EVENT_BREAK_EFFECT			=1050	--(unused, not available in YGOPro Percy)
EVENT_SUMMON_SUCCESS		=1100	--(unused)
EVENT_FLIP_SUMMON_SUCCESS	=1101	--(unused)
EVENT_PLAY					=1102	--When a card is played in the Battle Area
EVENT_SUMMON				=1103	--(unused)
EVENT_FLIP_SUMMON			=1104	--(unused)
EVENT_SPSUMMON				=1105	--(unused)
EVENT_MSET					=1106	--(unused)
EVENT_SSET					=1107	--(unused)
EVENT_ABSORB				=1108	--When a card is placed under another card ("BT3-050 Majin Buu, Dawn of the Rampage")
EVENT_BE_PRE_MATERIAL		=1109	--(unused)
EVENT_DRAW					=1110	--(unused)
EVENT_DAMAGE				=1111	--When a card inflicts damage to a player's life ([Critical])
EVENT_RECOVER				=1112	--(unused)
EVENT_CHARGE_PHASE			=1113	--Charge Phase
EVENT_SUMMON_NEGATED		=1114	--(unused, not available in YGOPro Percy)
EVENT_FLIP_SUMMON_NEGATED	=1115	--(unused, not available in YGOPro Percy)
EVENT_SPSUMMON_NEGATED		=1116	--(unused, not available in YGOPro Percy)
EVENT_CONTROL_CHANGED		=1120	--When control of a card changes
EVENT_EQUIP					=1121	--(unused)
EVENT_ATTACK_ANNOUNCE		=1130	--When a card declares an attack
EVENT_BE_BATTLE_TARGET		=1131	--When a card is targeted for an attack
EVENT_OFFENSE_STEP			=1132	--Offense Step
EVENT_DAMAGING				=1133	--When a card is dealing damage ("BT3-060 Dauntless Spirit SSB Vegeta")
EVENT_DAMAGE_STEP			=1134	--Damage Step
EVENT_DAMAGE_CALCULATING	=1135	--(N/A)
EVENT_PRE_BATTLE_DAMAGE		=1136	--(unused)
EVENT_BATTLE_END			=1137	--(N/A)
EVENT_BATTLED				=1138	--After damage calculation
EVENT_BATTLE_KOING			=1139	--When a card KO-s a card by battle
EVENT_BATTLE_KOED			=1140	--When a card is KO-ed by battle
EVENT_DAMAGE_STEP_END		=1141	--At the end of a battle
EVENT_ATTACK_DISABLED		=1142	--(unused)
EVENT_BATTLE_DAMAGE			=1143	--(unused)
EVENT_TOSS_DICE				=1150	--(unused)
EVENT_TOSS_COIN				=1151	--(unused)
EVENT_TOSS_COIN_NEGATE		=1152	--(unused)
EVENT_TOSS_DICE_NEGATE		=1153	--(unused)
EVENT_LEVEL_UP				=1200	--(unused)
EVENT_PAY_LPCOST			=1201	--(unused)
EVENT_DETACH_MATERIAL		=1202	--(unused)
EVENT_RETURN_TO_GRAVE		=1203	--(unused)
EVENT_TURN_END				=1210	--At the end of the turn
EVENT_PHASE					=0x1000		--During a phase of a turn (combined with PHASE constant)
EVENT_PHASE_START			=0x2000		--At the start of a phase of a turn (combined with PHASE constant)
EVENT_ADD_COUNTER			=0x10000	--(unused, combined with counter ID)
EVENT_REMOVE_COUNTER		=0x20000	--(unused, combined with counter ID)
EVENT_CUSTOM				=0x10000000	--Custom event
--The following is only available in YGOPro DS
EVENT_COMBO					=CARD_BT1005_CHAMPA		--When a player combos with a card
EVENT_ATTACK_END			=CARD_BT1008_VADOS		--After a battle (Workaround to untap after a battle)
EVENT_BLOCK					=CARD_BT1087_FRIEZA		--When a card's [Blocker] skill is activated
EVENT_MOVE_LEADER			=CARD_BT2003_BABIDI		--When a player places their Leader Card in the Leader Area
EVENT_COMBO_END				=CARD_BT2010_SS2_VEGETA	--After a player combo-ed with a card
EVENT_MAIN_PHASE_START		=CARD_SENSING_OLD_KAI	--At the beginning of the Main Phase
EVENT_ACTIVATE_EXTRA_CARD	=CARD_P028_FRIEZA		--When an Extra Card's skill is activated
EVENT_MOVE_EXTRA_CARD		=CARD_PLANET_M2			--When a card is placed (not played) in the Battle Area
EVENT_TRIGGER_ACTIVATE_MAIN	=CARD_BT5002_PILAF		--Activate the [Activate: Main] skill of a card with a card's skill
--Effect Category
CATEGORY_BLOCKER		=0x1	--[Blocker] (required for "BT1-003 Assassin Hit")
CATEGORY_COUNTER		=0x2	--[Counter] (required for "BT1-031 God Break Son Goku")
CATEGORY_AUTO			=0x4	--[Auto] (required for "TB01-077 Frieza, Emperor of Universe 7")
CATEGORY_ACTIVATE		=0x8	--[Activate] (required for "TB01-077 Frieza, Emperor of Universe 7")
CATEGORY_EX_EVOLVE		=0x10	--[EX-Evolve] (required for "BT4-003 Triple Flash SS4 Son Goku")
CATEGORY_COUNTER_PLAY	=0x20	--[Counter: Play] (required for "BT4-122 Minus Kili Zone")
CATEGORY_UNION_FUSION	=0x40	--[Union-Fusion] (required for "P-069 Miracle Strike Gogeta")
--Hint
--Message displayed in the center of the screen
HINT_EVENT		=1	--(unused)
HINT_MESSAGE	=2	--Display a string
HINT_SELECTMSG	=3	--Display a selection message
HINT_OPSELECTED	=4	--Display the selected effect
HINT_EFFECT		=5	--(unused)
HINT_RACE		=6	--(unused)
HINT_ATTRIB		=7	--(unused)
HINT_CODE		=8	--(unused)
HINT_NUMBER		=9	--(unused)
HINT_CARD		=10	--Display the card name selected by the effect
HINT_ZONE		=11	--(unused, not available in YGOPro Percy)
--Card Hint
--Message displayed in the white frame that appears when you place the cursor on the card
CHINT_TURN		=1	--(unused)
CHINT_CARD		=2	--(unused)
CHINT_RACE		=3	--(unused)
CHINT_ATTRIBUTE	=4	--(unused)
CHINT_NUMBER	=5	--(unused)
CHINT_DESC		=6	--(unused)
--Opcode
OPCODE_ADD			=0x40000000	--(unused)
OPCODE_SUB			=0x40000001	--(unused)
OPCODE_MUL			=0x40000002	--(unused)
OPCODE_DIV			=0x40000003	--(unused)
OPCODE_AND			=0x40000004	--(unused)
OPCODE_OR			=0x40000005	--(unused)
OPCODE_NEG			=0x40000006	--(unused)
OPCODE_NOT			=0x40000007	--(unused)
OPCODE_ISCODE		=0x40000100	--(unused)
OPCODE_ISSETCARD	=0x40000101	--(unused)
OPCODE_ISTYPE		=0x40000102	--(unused)
OPCODE_ISRACE		=0x40000103	--(unused)
OPCODE_ISATTRIBUTE	=0x40000104	--(unused)
--Damage
DOUBLE_DAMAGE	=0x80000000	--(unused, not available in YGOPro Percy)
HALF_DAMAGE		=0x80000001	--(unused, not available in YGOPro Percy)
--Hint Message
--Message displayed at the top of the screen
HINTMSG_REDRAW			=500	--Select a card to replace.
HINTMSG_CHARGE			=501	--Select a card to use as energy from your hand.
HINTMSG_COMBO			=502	--Select a card to place in the Combo Area.
HINTMSG_PAYENERGY		=503	--Select a card to use as energy.
HINTMSG_TARGET			=504	--Select a card to target.
HINTMSG_DROP			=505	--Select a card to drop.
HINTMSG_EVOLVE			=506	--Select a card to evolve.
HINTMSG_ATOHAND			=507	--Select a card to add to your hand.
HINTMSG_PLAY			=508	--Select a card to play.
HINTMSG_EVOLVEINTO		=509	--Select a card to evolve into.
HINTMSG_KO				=510	--Select a card to KO.
HINTMSG_TOACTIVE		=511	--Select a card to switch to Active Mode.
HINTMSG_RTOHAND			=512	--Select a card to return to the owner's hand.
HINTMSG_TODECK			=513	--Select a card to return to the owner's deck.
HINTMSG_TOENERGY		=514	--Select a card to add to the Energy Area.
HINTMSG_ANNOUNCECHOOSE	=515	--Choose how many cards?
HINTMSG_ACTIVATECARD	=516	--Select a card to activate.
HINTMSG_CONFIRM			=517	--Select a card to reveal.
HINTMSG_TOREST			=518	--Select a card to switch to Rest Mode.
HINTMSG_ANNOUNCEDROP	=519	--Drop how many cards?
HINTMSG_TOBATTLE		=520	--Select a card to place in the Battle Area.
HINTMSG_ABSORB			=521	--Select a card to absorb.
HINTMSG_FUSE			=522	--Select a card to fuse.
HINTMSG_KEYSKILL		=523	--Select a keyword skill.
HINTMSG_REMOVE			=524	--Select a card to remove from the game.
HINTMSG_WARP			=525	--Select a card to warp.
HINTMSG_GAINCONTROL		=526	--Select a card to gain control.
HINTMSG_ANNOUNCEABSORB	=527	--Absorb how many cards?
HINTMSG_ANNOUNCEDRAW	=528	--Draw how many cards?
HINTMSG_ACTIVATESKILL	=529	--Select a card to activate its skill.
--Information displayed in a dialog box
ERROR_DECKCOUNT				=1450	--Your deck must have 50 cards!
ERROR_TOKEN					=1451	--You cannot include tokens in your deck!
ERROR_LEADERCOUNT			=1452	--You require exactly 1 Leader Card!
ERROR_ULTIMATECOUNT			=1453	--You cannot include more than 1 card with [Ultimate] in your deck!
ERROR_SUPERCOMBOCOUNT		=1454	--You cannot include more than 4 cards with [Super Combo] in your deck!
ERROR_NONUNIVERSE7			=1455	--You cannot include non-<<Universe 7>> cards in your deck!
ERROR_NONUNIVERSE			=1456	--You cannot include non-<<Universe>> cards in your deck!
ERROR_NONWORLDTOURNAMENT	=1457	--You cannot include non-<<World Tournament>> cards in your deck!
ERROR_COST6MORE				=1458	--You cannot include cards with energy costs of 6 or more in your deck!
ERROR_DRAGONBALLCOUNT		=1459	--You cannot include more than 7 cards with [Dragon Ball] in your deck!
ERROR_COST5MORE				=1460	--You cannot include cards with energy costs of 5 or more in your deck!
ERROR_NOBZONES				=1630	--You may place up to 5 Battle Cards in your Battle Area when playing with this app. However, there is no limit to the number of Battle Cards in the Battle Area when playing the actual card game.
ERROR_NOTARGETS				=1631	--There is no applicable card.
ERROR_ENERGYLIMIT			=1632	--A skill is preventing you from adding a card to your energy.
--Yes No Message (for Duel.SelectYesNo)
YESNOMSG_MULLIGAN		=600	--Redraw cards in your hand?
YESNOMSG_CONFIRMAWAKEN	=601	--Are you sure you want to use your Leader's [Awaken] skill?
YESNOMSG_DROP			=602	--Drop a card?
YESNOMSG_CHOOSE			=603	--Choose a card?
YESNOMSG_DAMAGESELF		=604	--Inflict damage to your life?
YESNOMSG_DRAW			=605	--Draw a card?
YESNOMSG_ABSORB			=606	--Absorb a card?
YESNOMSG_WARP			=607	--Send a card to the Warp?
YESNOMSG_PLAY			=608	--Play a Battle Card?
YESNOMSG_TODECK			=609	--Return a card to its owner's deck?
YESNOMSG_CONFIRMWISH	=610	--Are you sure you want use your Leader's [Wish] skill?
--Option (for Duel.SelectOption)
OPTION_HEADS	=60	--(unused)
OPTION_TAILS	=61	--(unused)
--Description (for SetDescription, EFFECT_FLAG_CLIENT_HINT)
DESC_COMBO				=110	--Comboing
DESC_REST				=111	--Rest Mode
DESC_PLAY				=1152	--Play
DESC_CHARGE_UNTAP		=1650	--Switch all of your Rest Mode cards to Active Mode.
DESC_CHARGE_ENERGY		=1651	--Place a card in your hand in the Energy Area.
DESC_KO_GUARD			=1652	--KO the guard card.
DESC_CONFIRM_LEADER		=1653	--Confirm opponent's Leader Card. Click OK to continue.
DESC_CHARGEPHASE		=1660	--(reserved) Charge Phase
DESC_MAINPHASE			=1661	--(reserved) Main Phase
DESC_OFFENSE_STEP		=1662	--Offense Step
DESC_DEFENSE_STEP		=1663	--Defense Step
DESC_AWAKEN				=1800	--[Awaken]
DESC_DOUBLE_STRIKE		=1801	--[Double Strike]
DESC_EVOLVE				=1802	--[Evolve]
DESC_TRIPLE_STRIKE		=1803	--[Triple Strike]
DESC_DUAL_ATTACK		=1804	--[Dual Attack]
DESC_BLOCKER			=1805	--[Blocker]
DESC_CRITICAL			=1806	--[Critical]
DESC_QUAD_STRIKE		=1807	--[Quadruple Strike]
DESC_REVENGE			=1808	--[Revenge]
DESC_FIELD				=1809	--[Field]
DESC_UNION_POTARA		=1810	--[Union-Potara]
DESC_UNION_FUSION		=1811	--[Union-Fusion]
DESC_UNION_ABSORB		=1812	--[Union-Absorb]
DESC_INDESTRUCTIBLE		=1813	--[Indestructible]
DESC_ULTIMATE			=1814	--[Ultimate]
DESC_TRIPLE_ATTACK		=1815	--[Triple Attack]
DESC_OVER_REALM			=1816	--[Over Realm]
DESC_EX_EVOLVE			=1817	--[EX-Evolve]
DESC_BARRIER			=1818	--[Barrier]
DESC_SUPER_COMBO		=1819	--[Super Combo]
DESC_XENO_EVOLVE		=1820	--[Xeno-Evolve]
DESC_UNIVERSE_7			=1821	--[Warrior of Universe 7]
DESC_VICTORY_STRIKE		=1822	--[Victory Strike]
DESC_DEFLECT			=1823	--[Deflect]
DESC_BOND				=1824	--[Bond]
DESC_SWAP				=1825	--[Swap]
DESC_WORMHOLE			=1826	--[Wormhole]
DESC_DARK_OVER_REALM	=1827	--[Dark Over Realm]
DESC_BURST				=1828	--[Burst]
DESC_SPARKING			=1829	--[Sparking]
DESC_DRAGON_BALL		=1830	--[Dragon Ball]
DESC_WISH				=1831	--[Wish]
--Timing
--Free Chain activation timing
TIMING_DRAW_PHASE		=0x1		--(unused)
TIMING_STANDBY_PHASE	=0x2		--(unused)
TIMING_MAIN_END			=0x4		--End of Main Phase
TIMING_BATTLE_START		=0x8		--Start Step
TIMING_BATTLE_END		=0x10		--(unused)
TIMING_END_PHASE		=0x20		--(unused)
TIMING_SUMMON			=0x40		--(unused)
TIMING_SPSUMMON			=0x80		--(unused)
TIMING_FLIPSUMMON		=0x100		--(unused)
TIMING_MSET				=0x200		--(unused)
TIMING_SSET				=0x400		--(unused)
TIMING_POS_CHANGE		=0x800		--(unused)
TIMING_ATTACK			=0x1000		--(unused)
TIMING_DAMAGE_STEP		=0x2000		--(unused)
TIMING_DAMAGE_CAL		=0x4000		--(unused)
TIMING_CHAIN_END		=0x8000		--(unused)
TIMING_DRAW				=0x10000	--(unused)
TIMING_DAMAGE			=0x20000	--(unused)
TIMING_RECOVER			=0x40000	--(unused)
TIMING_DESTROY			=0x80000	--(unused)
TIMING_REMOVE			=0x100000	--(unused)
TIMING_TOHAND			=0x200000	--(unused)
TIMING_TODECK			=0x400000	--(unused)
TIMING_TOGRAVE			=0x800000	--(unused)
TIMING_BATTLE_PHASE		=0x1000000	--(unused)
TIMING_EQUIP			=0x2000000	--(unused)
TIMING_BATTLE_STEP_END	=0x4000000	--(unused)
TIMING_MAIN_PHASE		=TIMING_MAIN_END+TIMING_BATTLE_START	--Main Phase
--Timing combinations
TIMINGS_CHECK_MONSTER	=0x1c0		--(unused) TIMING_SUMMON+TIMING_SPSUMMON+TIMING_FLIPSUMMON
--Global Flag
--Special effect flag
GLOBALFLAG_DECK_REVERSE_CHECK	=0x1	--(unused)
GLOBALFLAG_BRAINWASHING_CHECK	=0x2	--(unused)
GLOBALFLAG_SCRAP_CHIMERA		=0x4	--(unused)
GLOBALFLAG_DELAYED_QUICKEFFECT	=0x8	--(N/A)
GLOBALFLAG_DETACH_EVENT			=0x10	--(unused)
GLOBALFLAG_MUST_BE_SMATERIAL	=0x20	--(unused)
GLOBALFLAG_SPSUMMON_COUNT		=0x40	--(unused)
GLOBALFLAG_XMAT_COUNT_LIMIT		=0x80	--(unused)
GLOBALFLAG_SELF_TOGRAVE			=0x100	--(unused)
GLOBALFLAG_SPSUMMON_ONCE		=0x200	--(unused)
GLOBALFLAG_TUNE_MAGICIAN		=0x400	--(unused)
--Effect Count Code
--Limit the number of effects that can be used
EFFECT_COUNT_CODE_OATH		=0x10000000	--(unused)
EFFECT_COUNT_CODE_DUEL		=0x20000000	--(unused)
EFFECT_COUNT_CODE_SINGLE	=0x1		--(unused)
--Duel Options
DUEL_TEST_MODE			=0x01	--Test mode (not currently available)
DUEL_ATTACK_FIRST_TURN	=0x02	--Can attack during the first turn (for puzzles)
DUEL_NO_CHAIN_HINT		=0x04	--(N/A)
DUEL_OBSOLETE_RULING	=0x08	--Use old rules
DUEL_PSEUDO_SHUFFLE		=0x10	--Do not shuffle Deck
DUEL_TAG_MODE			=0x20	--2v2
DUEL_SIMPLE_AI			=0x40	--Semi-automatic AI (for puzzles)
SPEED_DUEL				=0x80	--Speed Duel (only available in YGOPro Percy)
--Activity Counter
--global: 1-6 (binary: 5,6)
--custom: 1-5,7 (binary: 1-5)
ACTIVITY_SUMMON			=1	--(unused)
ACTIVITY_NORMALSUMMON	=2	--(unused)
ACTIVITY_SPSUMMON		=3	--(unused)
ACTIVITY_FLIPSUMMON		=4	--(unused)
ACTIVITY_ATTACK			=5	--(unused)
ACTIVITY_BATTLE_PHASE	=6	--(unused, not available in Duel.AddCustomActivityCounter)
ACTIVITY_CHAIN			=7	--(unused, only available in Duel.AddCustomActivityCounter)
--Announce Type
ANNOUNCE_CARD			=0x7	--(unused, only available in YGOPro Percy)
ANNOUNCE_CARD_FILTER	=0x8	--(unused, only available in YGOPro Percy)
